

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**

 @author normanel
 */
public class NewJFrame extends javax.swing.JFrame
{

   /**
    Creates new form NewJFrame
    */
   public NewJFrame()
   {
      initComponents();
   }

   /**
    This method is called from within the constructor to initialize the form.
    WARNING: Do NOT modify this code. The content of this method is always
    regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataSetDialog = new CustomJDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        firstYearTextField = new javax.swing.JTextField();
        sampleIDLengthTextField = new javax.swing.JTextField();
        lastYearTextField1 = new javax.swing.JTextField();
        numberOfSamplesTextField = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JButton();
        saveDataSetBtn1 = new javax.swing.JButton();
        importDataFileChooser = new javax.swing.JFileChooser();
        siteInfoDialog = new CustomJDialog();
        jLabel6 = new javax.swing.JLabel();
        txtSiteName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSiteCode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtYearStart = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtYearEnd = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCollectors = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCrossDaters = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNumSamples = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtSpeciesName = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCommonName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtHabitat = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtCountry = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtCounty = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtPark = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtForest = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtDistrict = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtTownship = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtRange = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtSection = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtQuarterSection = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtUTMEasting = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtUTMNorthing = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtLat = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtLong = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtTopoMap = new javax.swing.JTextField();
        txtLowestElev = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtHighestElev = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtSlope = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtAspect = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtAreaSampled = new javax.swing.JTextField();
        txtSubstrate = new javax.swing.JLabel();
        jTextField31 = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        utilitiesDialog = new CustomJDialog();
        showSeriesBtn = new javax.swing.JButton();
        insertSeriesBtn = new javax.swing.JButton();
        renameSeriesBtn = new javax.swing.JButton();
        deleteSeriesBtn = new javax.swing.JButton();
        moveSeriesBtn = new javax.swing.JButton();
        sortSeriesBtn = new javax.swing.JButton();
        mergeDataSetsBtn = new javax.swing.JButton();
        quitBtn = new javax.swing.JButton();
        showSeriesDialog = new CustomJDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel37 = new javax.swing.JLabel();
        errorDialog = new CustomJDialog();
        insertDialog = new CustomJDialog();
        jLabel38 = new javax.swing.JLabel();
        insertSeriesTextField = new javax.swing.JTextField();
        renameSeriesDialog = new CustomJDialog();
        renameTextBox = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        oldSeriesIDLabel = new javax.swing.JLabel();
        newSeriesIDTextField = new javax.swing.JTextField();
        deleteSeriesDialog = new CustomJDialog();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        deleteSeriesBeginTextBox = new javax.swing.JTextField();
        deleteSeriesEndTextBox = new javax.swing.JTextField();
        moveSeriesDialog = new CustomJDialog();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        seriesMoveToTextBox = new javax.swing.JTextField();
        moveWhichSeriesTextBox = new javax.swing.JTextField();
        sortSeriesDialog = new CustomJDialog();
        sortDataBtn = new javax.swing.JButton();
        sortSeriesQuitBtn = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        sortSeriesStatusLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        sortSeriesList = new javax.swing.JList();
        mergeDataSetDialog = new CustomJDialog();
        jLabel47 = new javax.swing.JLabel();
        mergeChoose2FileBtn = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        mergeChoose1FileBtn = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        outputFileTextBox = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        retrieveInfoList = new javax.swing.JList();
        mergeDataBtn = new javax.swing.JButton();
        mergeQuitBtn = new javax.swing.JButton();
        enterFireHistoryDialog = new CustomJDialog();
        utilBtn = new javax.swing.JButton();
        newDataBtn = new javax.swing.JButton();
        importBtn = new javax.swing.JButton();
        changeSettingBtn = new javax.swing.JButton();
        fileNameTextField = new javax.swing.JTextField();
        sampleIDTextField = new javax.swing.JTextField();
        beginYearTextField = new javax.swing.JTextField();
        fireHistoryBtn = new javax.swing.JButton();
        siteInfoBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();

        dataSetDialog.setTitle("Setup New Dataset");
        dataSetDialog.setAlwaysOnTop(true);
        dataSetDialog.setMinimumSize(new java.awt.Dimension(200, 400));
        dataSetDialog.setModal(true);
        dataSetDialog.setResizable(false);

        jLabel1.setText("First year of the data set");

        jLabel2.setText("Last year of the data set");

        jLabel3.setText("Number of Samples");

        jLabel4.setText("Sample ID length");

        firstYearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstYearTextFieldActionPerformed(evt);
            }
        });

        numberOfSamplesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfSamplesTextFieldActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");

        saveDataSetBtn1.setText("Save");

        javax.swing.GroupLayout dataSetDialogLayout = new javax.swing.GroupLayout(dataSetDialog.getContentPane());
        dataSetDialog.getContentPane().setLayout(dataSetDialogLayout);
        dataSetDialogLayout.setHorizontalGroup(
            dataSetDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataSetDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataSetDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sampleIDLengthTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numberOfSamplesTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lastYearTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstYearTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dataSetDialogLayout.createSequentialGroup()
                        .addGroup(dataSetDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addGroup(dataSetDialogLayout.createSequentialGroup()
                                .addComponent(saveDataSetBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dataSetDialogLayout.setVerticalGroup(
            dataSetDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataSetDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(firstYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastYearTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberOfSamplesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(sampleIDLengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dataSetDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveDataSetBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        siteInfoDialog.setMinimumSize(new java.awt.Dimension(700, 550));
        siteInfoDialog.setModal(true);
        siteInfoDialog.setPreferredSize(new java.awt.Dimension(700, 550));
        siteInfoDialog.setResizable(false);

        jLabel6.setText("Name of Site");

        jLabel7.setText("Site Code");

        jLabel8.setText("Collection Date");

        jLabel5.setText("Start Year");

        jLabel9.setText("End Year");

        jLabel10.setText("Collectors");

        jLabel11.setText("CrossDaters");

        jLabel12.setText("Number Samples");

        jLabel13.setText("Species Name");

        jLabel14.setText("Common Name");

        jLabel15.setText("Habitat Type");

        jLabel16.setText("Country");

        jLabel17.setText("State");

        jLabel18.setText("County");

        jLabel19.setText("Park/Monument");

        jLabel20.setText("National Forest");

        jLabel21.setText("Ranger District");

        jLabel22.setText("Township");

        jLabel23.setText("Range");

        jLabel24.setText("Section");

        jLabel25.setText("Quarter Section");

        jLabel26.setText("UTM easting");

        jLabel27.setText("UTM northing");

        jLabel28.setText("Latitude");

        jLabel29.setText("Longtitude");

        jLabel30.setText("Topographic Map");

        jLabel31.setText("Lowest Elev.");

        jLabel32.setText("Highest Elev.");

        jLabel33.setText("Slope");

        jLabel34.setText("Aspect");

        jLabel35.setText("Area Sampled");

        txtSubstrate.setText("Substrate Type");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setText("Save");

        javax.swing.GroupLayout siteInfoDialogLayout = new javax.swing.GroupLayout(siteInfoDialog.getContentPane());
        siteInfoDialog.getContentPane().setLayout(siteInfoDialogLayout);
        siteInfoDialogLayout.setHorizontalGroup(
            siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siteInfoDialogLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(siteInfoDialogLayout.createSequentialGroup()
                        .addComponent(txtCommonName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtCounty, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtSection, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(siteInfoDialogLayout.createSequentialGroup()
                        .addGroup(siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAreaSampled, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(siteInfoDialogLayout.createSequentialGroup()
                                .addComponent(txtQuarterSection, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(siteInfoDialogLayout.createSequentialGroup()
                .addGroup(siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(siteInfoDialogLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(siteInfoDialogLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtSiteName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtPark, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtLat, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(siteInfoDialogLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(siteInfoDialogLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtSiteCode, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtForest, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtLong, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(siteInfoDialogLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(siteInfoDialogLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtTopoMap, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(siteInfoDialogLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtYearStart, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txtYearEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(siteInfoDialogLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(280, 280, 280)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(siteInfoDialogLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtCollectors, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtUTMEasting, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtLowestElev, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(siteInfoDialogLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(280, 280, 280)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(siteInfoDialogLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtCrossDaters, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtUTMNorthing, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtHighestElev, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(siteInfoDialogLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(siteInfoDialogLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtNumSamples, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtTownship, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(txtSlope, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(siteInfoDialogLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(siteInfoDialogLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtSpeciesName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtRange, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(txtAspect, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(siteInfoDialogLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(siteInfoDialogLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(siteInfoDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtSubstrate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        siteInfoDialogLayout.setVerticalGroup(
            siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siteInfoDialogLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel19)
                    .addComponent(jLabel28))
                .addGap(6, 6, 6)
                .addGroup(siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSiteName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel20)
                    .addComponent(jLabel29))
                .addGap(6, 6, 6)
                .addGroup(siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSiteCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtForest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel21)
                    .addComponent(jLabel30))
                .addGap(6, 6, 6)
                .addGroup(siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(txtDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTopoMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtYearStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYearEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel26)
                    .addComponent(jLabel31))
                .addGap(6, 6, 6)
                .addGroup(siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCollectors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUTMEasting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLowestElev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel27)
                    .addComponent(jLabel32))
                .addGap(6, 6, 6)
                .addGroup(siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCrossDaters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUTMNorthing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHighestElev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16)
                    .addComponent(jLabel22)
                    .addComponent(jLabel33))
                .addGap(6, 6, 6)
                .addGroup(siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumSamples, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTownship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSlope, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17)
                    .addComponent(jLabel23)
                    .addComponent(jLabel34))
                .addGap(6, 6, 6)
                .addGroup(siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSpeciesName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAspect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18)
                    .addComponent(jLabel24))
                .addGap(5, 5, 5)
                .addGroup(siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCommonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCounty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSave)))
                .addGap(8, 8, 8)
                .addGroup(siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(siteInfoDialogLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(6, 6, 6)
                        .addComponent(txtHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(siteInfoDialogLayout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(6, 6, 6)
                        .addComponent(txtAreaSampled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(siteInfoDialogLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(5, 5, 5)
                        .addGroup(siteInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQuarterSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(txtSubstrate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        utilitiesDialog.setTitle("Utilities");
        utilitiesDialog.setResizable(false);

        showSeriesBtn.setText("Show Series");
        showSeriesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSeriesBtnActionPerformed(evt);
            }
        });

        insertSeriesBtn.setText("Insert Series");
        insertSeriesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertSeriesBtnActionPerformed(evt);
            }
        });

        renameSeriesBtn.setText("Rename Series");
        renameSeriesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameSeriesBtnActionPerformed(evt);
            }
        });

        deleteSeriesBtn.setText("Delete Series");
        deleteSeriesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSeriesBtnActionPerformed(evt);
            }
        });

        moveSeriesBtn.setText("Move Series");
        moveSeriesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveSeriesBtnActionPerformed(evt);
            }
        });

        sortSeriesBtn.setText("Sort Series");
        sortSeriesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortSeriesBtnActionPerformed(evt);
            }
        });

        mergeDataSetsBtn.setText("Merge two data sets");
        mergeDataSetsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mergeDataSetsBtnActionPerformed(evt);
            }
        });

        quitBtn.setText("Quit");

        javax.swing.GroupLayout utilitiesDialogLayout = new javax.swing.GroupLayout(utilitiesDialog.getContentPane());
        utilitiesDialog.getContentPane().setLayout(utilitiesDialogLayout);
        utilitiesDialogLayout.setHorizontalGroup(
            utilitiesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utilitiesDialogLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(utilitiesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showSeriesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insertSeriesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(renameSeriesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteSeriesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moveSeriesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sortSeriesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mergeDataSetsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(quitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        utilitiesDialogLayout.setVerticalGroup(
            utilitiesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utilitiesDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showSeriesBtn)
                .addGap(18, 18, 18)
                .addComponent(insertSeriesBtn)
                .addGap(18, 18, 18)
                .addComponent(renameSeriesBtn)
                .addGap(18, 18, 18)
                .addComponent(deleteSeriesBtn)
                .addGap(18, 18, 18)
                .addComponent(moveSeriesBtn)
                .addGap(18, 18, 18)
                .addComponent(sortSeriesBtn)
                .addGap(18, 18, 18)
                .addComponent(mergeDataSetsBtn)
                .addGap(18, 18, 18)
                .addComponent(quitBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        showSeriesDialog.setTitle("Show Series");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Series");

        javax.swing.GroupLayout showSeriesDialogLayout = new javax.swing.GroupLayout(showSeriesDialog.getContentPane());
        showSeriesDialog.getContentPane().setLayout(showSeriesDialogLayout);
        showSeriesDialogLayout.setHorizontalGroup(
            showSeriesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showSeriesDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(showSeriesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        showSeriesDialogLayout.setVerticalGroup(
            showSeriesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showSeriesDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        insertDialog.setTitle("Insert Series");

        jLabel38.setText("Insert at which series number: ");

        insertSeriesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertSeriesTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout insertDialogLayout = new javax.swing.GroupLayout(insertDialog.getContentPane());
        insertDialog.getContentPane().setLayout(insertDialogLayout);
        insertDialogLayout.setHorizontalGroup(
            insertDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insertSeriesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        insertDialogLayout.setVerticalGroup(
            insertDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(insertSeriesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        renameSeriesDialog.setTitle("Rename Series");

        jLabel39.setText("Rename which series number: ");

        jLabel40.setText("New Series ID: ");

        jLabel41.setText("Old Series ID: ");

        oldSeriesIDLabel.setText("xxxxx");

        javax.swing.GroupLayout renameSeriesDialogLayout = new javax.swing.GroupLayout(renameSeriesDialog.getContentPane());
        renameSeriesDialog.getContentPane().setLayout(renameSeriesDialogLayout);
        renameSeriesDialogLayout.setHorizontalGroup(
            renameSeriesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(renameSeriesDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(renameSeriesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(renameSeriesDialogLayout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(renameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(renameSeriesDialogLayout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oldSeriesIDLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newSeriesIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        renameSeriesDialogLayout.setVerticalGroup(
            renameSeriesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(renameSeriesDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(renameSeriesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(renameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(renameSeriesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oldSeriesIDLabel)
                    .addComponent(jLabel40)
                    .addComponent(newSeriesIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel42.setText("Delete from series number:");

        jLabel43.setText("to series number:");

        javax.swing.GroupLayout deleteSeriesDialogLayout = new javax.swing.GroupLayout(deleteSeriesDialog.getContentPane());
        deleteSeriesDialog.getContentPane().setLayout(deleteSeriesDialogLayout);
        deleteSeriesDialogLayout.setHorizontalGroup(
            deleteSeriesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteSeriesDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deleteSeriesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deleteSeriesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteSeriesBeginTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(deleteSeriesEndTextBox))
                .addContainerGap())
        );
        deleteSeriesDialogLayout.setVerticalGroup(
            deleteSeriesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteSeriesDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deleteSeriesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteSeriesBeginTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(deleteSeriesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(deleteSeriesEndTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        moveSeriesDialog.getContentPane().setLayout(null);

        jLabel44.setText("Move which series number: ");
        moveSeriesDialog.getContentPane().add(jLabel44);
        jLabel44.setBounds(0, 0, 150, 14);

        jLabel45.setText("To which series position: ");
        moveSeriesDialog.getContentPane().add(jLabel45);
        jLabel45.setBounds(0, 30, 140, 14);
        moveSeriesDialog.getContentPane().add(seriesMoveToTextBox);
        seriesMoveToTextBox.setBounds(220, 30, 90, 20);
        moveSeriesDialog.getContentPane().add(moveWhichSeriesTextBox);
        moveWhichSeriesTextBox.setBounds(220, 0, 100, 20);

        sortDataBtn.setText("Sort Data");

        sortSeriesQuitBtn.setText("Quit");

        jLabel46.setText("Status :");

        sortSeriesStatusLabel.setText("xxxxx");

        sortSeriesList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Inside year : Ascending", "Inside year : Descending", "Outside year : Ascending", "Outside year : Descending", " ", "Inside fire : Ascending", "Inside fire : descending", "Outside fire : Ascending", "Outside fire : descending", " ", "By Sample ID" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(sortSeriesList);

        javax.swing.GroupLayout sortSeriesDialogLayout = new javax.swing.GroupLayout(sortSeriesDialog.getContentPane());
        sortSeriesDialog.getContentPane().setLayout(sortSeriesDialogLayout);
        sortSeriesDialogLayout.setHorizontalGroup(
            sortSeriesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sortSeriesDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sortSeriesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(sortSeriesDialogLayout.createSequentialGroup()
                        .addComponent(sortDataBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(sortSeriesQuitBtn))
                    .addGroup(sortSeriesDialogLayout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sortSeriesStatusLabel)
                        .addGap(110, 110, 110))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        sortSeriesDialogLayout.setVerticalGroup(
            sortSeriesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sortSeriesDialogLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sortSeriesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(sortSeriesStatusLabel))
                .addGap(15, 15, 15)
                .addGroup(sortSeriesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortSeriesQuitBtn)
                    .addComponent(sortDataBtn))
                .addContainerGap())
        );

        jLabel47.setText("First data set to merge: ");

        mergeChoose2FileBtn.setText("choose file");
        mergeChoose2FileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mergeChoose2FileBtnActionPerformed(evt);
            }
        });

        jLabel48.setText("Second data set to merge: ");

        mergeChoose1FileBtn.setText("choose file");
        mergeChoose1FileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mergeChoose1FileBtnActionPerformed(evt);
            }
        });

        jLabel49.setText("Output file for merged matrix : ");

        jLabel50.setText("Retrieve Site info from: ");

        retrieveInfoList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "First", "Second", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(retrieveInfoList);

        mergeDataBtn.setText("Merge data sets");

        mergeQuitBtn.setText("Quit");

        javax.swing.GroupLayout mergeDataSetDialogLayout = new javax.swing.GroupLayout(mergeDataSetDialog.getContentPane());
        mergeDataSetDialog.getContentPane().setLayout(mergeDataSetDialogLayout);
        mergeDataSetDialogLayout.setHorizontalGroup(
            mergeDataSetDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mergeDataSetDialogLayout.createSequentialGroup()
                .addGroup(mergeDataSetDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mergeDataSetDialogLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(mergeDataSetDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mergeDataSetDialogLayout.createSequentialGroup()
                                .addComponent(mergeDataBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mergeQuitBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mergeDataSetDialogLayout.createSequentialGroup()
                                .addGroup(mergeDataSetDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mergeDataSetDialogLayout.createSequentialGroup()
                                        .addGroup(mergeDataSetDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(mergeDataSetDialogLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(mergeDataSetDialogLayout.createSequentialGroup()
                                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(mergeDataSetDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(outputFileTextBox)
                                    .addComponent(mergeChoose2FileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mergeChoose1FileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(mergeDataSetDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        mergeDataSetDialogLayout.setVerticalGroup(
            mergeDataSetDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mergeDataSetDialogLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(mergeDataSetDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(mergeChoose1FileBtn))
                .addGap(18, 18, 18)
                .addGroup(mergeDataSetDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(mergeChoose2FileBtn))
                .addGap(18, 18, 18)
                .addGroup(mergeDataSetDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel49)
                    .addComponent(outputFileTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jLabel50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mergeDataSetDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mergeQuitBtn)
                    .addComponent(mergeDataBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout enterFireHistoryDialogLayout = new javax.swing.GroupLayout(enterFireHistoryDialog.getContentPane());
        enterFireHistoryDialog.getContentPane().setLayout(enterFireHistoryDialogLayout);
        enterFireHistoryDialogLayout.setHorizontalGroup(
            enterFireHistoryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        enterFireHistoryDialogLayout.setVerticalGroup(
            enterFireHistoryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(Constants.PROGRAM_NAME);
        setResizable(false);

        utilBtn.setLabel("Utilities");
        utilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utilBtnActionPerformed(evt);
            }
        });

        newDataBtn.setText("Set up new data set");
        newDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDataBtnActionPerformed(evt);
            }
        });

        importBtn.setText("Import Data");
        importBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importBtnActionPerformed(evt);
            }
        });

        changeSettingBtn.setText("Change settings in data set");
        changeSettingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSettingBtnActionPerformed(evt);
            }
        });

        fileNameTextField.setText("Provide a file name here");

        sampleIDTextField.setText("Enter sample ID here");

        beginYearTextField.setText("Enter beginning year here");

        fireHistoryBtn.setText("Edit fire history data here");
        fireHistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fireHistoryBtnActionPerformed(evt);
            }
        });

        siteInfoBtn.setText("Edit site info here");
        siteInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siteInfoBtnActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fireHistoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(siteInfoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(beginYearTextField)
                    .addComponent(sampleIDTextField)
                    .addComponent(fileNameTextField)
                    .addComponent(changeSettingBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(importBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newDataBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(utilBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(utilBtn)
                .addGap(11, 11, 11)
                .addComponent(newDataBtn)
                .addGap(12, 12, 12)
                .addComponent(importBtn)
                .addGap(12, 12, 12)
                .addComponent(changeSettingBtn)
                .addGap(12, 12, 12)
                .addComponent(fileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(sampleIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(beginYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(fireHistoryBtn)
                .addGap(7, 7, 7)
                .addComponent(siteInfoBtn)
                .addGap(7, 7, 7)
                .addComponent(saveBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        utilBtn.getAccessibleContext().setAccessibleName("utilitiesBtn");
        newDataBtn.getAccessibleContext().setAccessibleName("newDataBtn");
        importBtn.getAccessibleContext().setAccessibleName("importDataBtn");

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void utilBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_utilBtnActionPerformed
   {//GEN-HEADEREND:event_utilBtnActionPerformed
      
       this.utilitiesDialog.setVisible(true);
   }//GEN-LAST:event_utilBtnActionPerformed

   private void newDataBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newDataBtnActionPerformed
   {//GEN-HEADEREND:event_newDataBtnActionPerformed
      //dataSetDialogLabel.setText("Set up new data set");
      dataSetDialog.setTitle("Set up new data set");
      dataSetDialog.setVisible(true);
   }//GEN-LAST:event_newDataBtnActionPerformed

   private void importBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_importBtnActionPerformed
   {//GEN-HEADEREND:event_importBtnActionPerformed
      this.importDataFileChooser.showOpenDialog(this);
   }//GEN-LAST:event_importBtnActionPerformed

   private void numberOfSamplesTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberOfSamplesTextFieldActionPerformed
   {//GEN-HEADEREND:event_numberOfSamplesTextFieldActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_numberOfSamplesTextFieldActionPerformed

   private void changeSettingBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_changeSettingBtnActionPerformed
   {//GEN-HEADEREND:event_changeSettingBtnActionPerformed
      //dataSetDialogLabel.setText("Change settings in data set");
       dataSetDialog.setTitle("Change settings in data set");
      dataSetDialog.setVisible(true);
   }//GEN-LAST:event_changeSettingBtnActionPerformed

   private void siteInfoBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_siteInfoBtnActionPerformed
   {//GEN-HEADEREND:event_siteInfoBtnActionPerformed
      this.siteInfoDialog.setVisible(true);
   }//GEN-LAST:event_siteInfoBtnActionPerformed

   private void showSeriesBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_showSeriesBtnActionPerformed
   {//GEN-HEADEREND:event_showSeriesBtnActionPerformed
      this.showSeriesDialog.setVisible(true);
   }//GEN-LAST:event_showSeriesBtnActionPerformed

   private void insertSeriesBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_insertSeriesBtnActionPerformed
   {//GEN-HEADEREND:event_insertSeriesBtnActionPerformed
      this.insertDialog.setVisible(true);
   }//GEN-LAST:event_insertSeriesBtnActionPerformed

   private void renameSeriesBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_renameSeriesBtnActionPerformed
   {//GEN-HEADEREND:event_renameSeriesBtnActionPerformed
      this.renameSeriesDialog.setVisible(true);
   }//GEN-LAST:event_renameSeriesBtnActionPerformed

   private void deleteSeriesBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_deleteSeriesBtnActionPerformed
   {//GEN-HEADEREND:event_deleteSeriesBtnActionPerformed
      deleteSeriesDialog.setVisible(true);
   }//GEN-LAST:event_deleteSeriesBtnActionPerformed

   private void moveSeriesBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_moveSeriesBtnActionPerformed
   {//GEN-HEADEREND:event_moveSeriesBtnActionPerformed
      this.moveSeriesBtn.setVisible(true);
   }//GEN-LAST:event_moveSeriesBtnActionPerformed

   private void sortSeriesBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sortSeriesBtnActionPerformed
   {//GEN-HEADEREND:event_sortSeriesBtnActionPerformed
      sortSeriesDialog.setVisible(true);
   }//GEN-LAST:event_sortSeriesBtnActionPerformed

   private void mergeDataSetsBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mergeDataSetsBtnActionPerformed
   {//GEN-HEADEREND:event_mergeDataSetsBtnActionPerformed
      this.mergeDataSetDialog.setVisible(true);
   }//GEN-LAST:event_mergeDataSetsBtnActionPerformed

   private void mergeChoose2FileBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mergeChoose2FileBtnActionPerformed
   {//GEN-HEADEREND:event_mergeChoose2FileBtnActionPerformed
      this.importDataFileChooser.setVisible(true);
   }//GEN-LAST:event_mergeChoose2FileBtnActionPerformed

   private void mergeChoose1FileBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mergeChoose1FileBtnActionPerformed
   {//GEN-HEADEREND:event_mergeChoose1FileBtnActionPerformed
      this.importDataFileChooser.setVisible(true);
   }//GEN-LAST:event_mergeChoose1FileBtnActionPerformed

   private void fireHistoryBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fireHistoryBtnActionPerformed
   {//GEN-HEADEREND:event_fireHistoryBtnActionPerformed
      this.enterFireHistoryDialog.setVisible(true);
   }//GEN-LAST:event_fireHistoryBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveBtnActionPerformed

    private void firstYearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstYearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstYearTextFieldActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void insertSeriesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertSeriesTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertSeriesTextFieldActionPerformed

   /**
    @param args the command line arguments
    */
   public static void main(String args[])
   {
      /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try
      {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
         {
            if ("Nimbus".equals(info.getName()))
            {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      }
      catch (ClassNotFoundException ex)
      {
         java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (InstantiationException ex)
      {
         java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (IllegalAccessException ex)
      {
         java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (javax.swing.UnsupportedLookAndFeelException ex)
      {
         java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
        //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new NewJFrame().setVisible(true);
         }
      });
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField beginYearTextField;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton changeSettingBtn;
    private javax.swing.JDialog dataSetDialog;
    private javax.swing.JTextField deleteSeriesBeginTextBox;
    private javax.swing.JButton deleteSeriesBtn;
    private javax.swing.JDialog deleteSeriesDialog;
    private javax.swing.JTextField deleteSeriesEndTextBox;
    private javax.swing.JDialog enterFireHistoryDialog;
    private javax.swing.JDialog errorDialog;
    private javax.swing.JTextField fileNameTextField;
    private javax.swing.JButton fireHistoryBtn;
    private javax.swing.JTextField firstYearTextField;
    private javax.swing.JButton importBtn;
    private javax.swing.JFileChooser importDataFileChooser;
    private javax.swing.JDialog insertDialog;
    private javax.swing.JButton insertSeriesBtn;
    private javax.swing.JTextField insertSeriesTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField lastYearTextField1;
    private javax.swing.JButton mergeChoose1FileBtn;
    private javax.swing.JButton mergeChoose2FileBtn;
    private javax.swing.JButton mergeDataBtn;
    private javax.swing.JDialog mergeDataSetDialog;
    private javax.swing.JButton mergeDataSetsBtn;
    private javax.swing.JButton mergeQuitBtn;
    private javax.swing.JButton moveSeriesBtn;
    private javax.swing.JDialog moveSeriesDialog;
    private javax.swing.JTextField moveWhichSeriesTextBox;
    private javax.swing.JButton newDataBtn;
    private javax.swing.JTextField newSeriesIDTextField;
    private javax.swing.JTextField numberOfSamplesTextField;
    private javax.swing.JLabel oldSeriesIDLabel;
    private javax.swing.JTextField outputFileTextBox;
    private javax.swing.JButton quitBtn;
    private javax.swing.JButton renameSeriesBtn;
    private javax.swing.JDialog renameSeriesDialog;
    private javax.swing.JTextField renameTextBox;
    private javax.swing.JList retrieveInfoList;
    private javax.swing.JTextField sampleIDLengthTextField;
    private javax.swing.JTextField sampleIDTextField;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton saveDataSetBtn1;
    private javax.swing.JTextField seriesMoveToTextBox;
    private javax.swing.JButton showSeriesBtn;
    private javax.swing.JDialog showSeriesDialog;
    private javax.swing.JButton siteInfoBtn;
    private javax.swing.JDialog siteInfoDialog;
    private javax.swing.JButton sortDataBtn;
    private javax.swing.JButton sortSeriesBtn;
    private javax.swing.JDialog sortSeriesDialog;
    private javax.swing.JList sortSeriesList;
    private javax.swing.JButton sortSeriesQuitBtn;
    private javax.swing.JLabel sortSeriesStatusLabel;
    private javax.swing.JTextField txtAreaSampled;
    private javax.swing.JTextField txtAspect;
    private javax.swing.JTextField txtCollectors;
    private javax.swing.JTextField txtCommonName;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtCounty;
    private javax.swing.JTextField txtCrossDaters;
    private javax.swing.JTextField txtDistrict;
    private javax.swing.JTextField txtForest;
    private javax.swing.JTextField txtHabitat;
    private javax.swing.JTextField txtHighestElev;
    private javax.swing.JTextField txtLat;
    private javax.swing.JTextField txtLong;
    private javax.swing.JTextField txtLowestElev;
    private javax.swing.JTextField txtNumSamples;
    private javax.swing.JTextField txtPark;
    private javax.swing.JTextField txtQuarterSection;
    private javax.swing.JTextField txtRange;
    private javax.swing.JTextField txtSection;
    private javax.swing.JTextField txtSiteCode;
    private javax.swing.JTextField txtSiteName;
    private javax.swing.JTextField txtSlope;
    private javax.swing.JTextField txtSpeciesName;
    private javax.swing.JTextField txtState;
    private javax.swing.JLabel txtSubstrate;
    private javax.swing.JTextField txtTopoMap;
    private javax.swing.JTextField txtTownship;
    private javax.swing.JTextField txtUTMEasting;
    private javax.swing.JTextField txtUTMNorthing;
    private javax.swing.JTextField txtYearEnd;
    private javax.swing.JTextField txtYearStart;
    private javax.swing.JButton utilBtn;
    private javax.swing.JDialog utilitiesDialog;
    // End of variables declaration//GEN-END:variables
}
