

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**

 @author normanel
 */
public class NewJFrame extends javax.swing.JFrame
{

   /**
    Creates new form NewJFrame
    */
   public NewJFrame()
   {
      initComponents();
   }

   /**
    This method is called from within the constructor to initialize the form.
    WARNING: Do NOT modify this code. The content of this method is always
    regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      dataSetDialog = new javax.swing.JDialog();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      firstYearTextField = new javax.swing.JTextField();
      sampleIDLengthTextField = new javax.swing.JTextField();
      lastYearTextField1 = new javax.swing.JTextField();
      numberOfSamplesTextField = new javax.swing.JTextField();
      cancelBtn = new javax.swing.JButton();
      saveDataSetBtn1 = new javax.swing.JButton();
      dataSetDialogLabel = new javax.swing.JLabel();
      importDataFileChooser = new javax.swing.JFileChooser();
      siteInfoDialog = new javax.swing.JDialog();
      jLabel6 = new javax.swing.JLabel();
      jTextField1 = new javax.swing.JTextField();
      jLabel7 = new javax.swing.JLabel();
      jTextField2 = new javax.swing.JTextField();
      jLabel8 = new javax.swing.JLabel();
      jTextField3 = new javax.swing.JTextField();
      jLabel5 = new javax.swing.JLabel();
      jTextField4 = new javax.swing.JTextField();
      jLabel9 = new javax.swing.JLabel();
      jLabel10 = new javax.swing.JLabel();
      jTextField5 = new javax.swing.JTextField();
      jLabel11 = new javax.swing.JLabel();
      jTextField6 = new javax.swing.JTextField();
      jLabel12 = new javax.swing.JLabel();
      jTextField7 = new javax.swing.JTextField();
      jLabel13 = new javax.swing.JLabel();
      jTextField8 = new javax.swing.JTextField();
      jLabel14 = new javax.swing.JLabel();
      jTextField9 = new javax.swing.JTextField();
      jLabel15 = new javax.swing.JLabel();
      jTextField10 = new javax.swing.JTextField();
      jLabel16 = new javax.swing.JLabel();
      jTextField11 = new javax.swing.JTextField();
      jLabel17 = new javax.swing.JLabel();
      jTextField12 = new javax.swing.JTextField();
      jLabel18 = new javax.swing.JLabel();
      jTextField13 = new javax.swing.JTextField();
      jLabel19 = new javax.swing.JLabel();
      jTextField14 = new javax.swing.JTextField();
      jLabel20 = new javax.swing.JLabel();
      jTextField15 = new javax.swing.JTextField();
      jLabel21 = new javax.swing.JLabel();
      jTextField16 = new javax.swing.JTextField();
      jLabel22 = new javax.swing.JLabel();
      jTextField17 = new javax.swing.JTextField();
      jLabel23 = new javax.swing.JLabel();
      jTextField18 = new javax.swing.JTextField();
      jLabel24 = new javax.swing.JLabel();
      jTextField19 = new javax.swing.JTextField();
      jLabel25 = new javax.swing.JLabel();
      jTextField20 = new javax.swing.JTextField();
      jLabel26 = new javax.swing.JLabel();
      jTextField21 = new javax.swing.JTextField();
      jLabel27 = new javax.swing.JLabel();
      jTextField22 = new javax.swing.JTextField();
      jLabel28 = new javax.swing.JLabel();
      jTextField23 = new javax.swing.JTextField();
      jLabel29 = new javax.swing.JLabel();
      jTextField24 = new javax.swing.JTextField();
      jLabel30 = new javax.swing.JLabel();
      jTextField25 = new javax.swing.JTextField();
      jTextField26 = new javax.swing.JTextField();
      jLabel31 = new javax.swing.JLabel();
      jTextField27 = new javax.swing.JTextField();
      jLabel32 = new javax.swing.JLabel();
      jTextField28 = new javax.swing.JTextField();
      jLabel33 = new javax.swing.JLabel();
      jTextField29 = new javax.swing.JTextField();
      jLabel34 = new javax.swing.JLabel();
      jLabel35 = new javax.swing.JLabel();
      jTextField30 = new javax.swing.JTextField();
      jLabel36 = new javax.swing.JLabel();
      jTextField31 = new javax.swing.JTextField();
      jButton1 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();
      utilitiesDialog = new javax.swing.JDialog();
      showSeriesBtn = new javax.swing.JButton();
      insertSeriesBtn = new javax.swing.JButton();
      renameSeriesBtn = new javax.swing.JButton();
      deleteSeriesBtn = new javax.swing.JButton();
      moveSeriesBtn = new javax.swing.JButton();
      sortSeriesBtn = new javax.swing.JButton();
      mergeDataSetsBtn = new javax.swing.JButton();
      quitBtn = new javax.swing.JButton();
      showSeriesDialog = new javax.swing.JDialog();
      jScrollPane1 = new javax.swing.JScrollPane();
      jList1 = new javax.swing.JList();
      jLabel37 = new javax.swing.JLabel();
      errorDialog = new javax.swing.JDialog();
      insertDialog = new javax.swing.JDialog();
      jLabel38 = new javax.swing.JLabel();
      insertSeriesTextField = new javax.swing.JTextField();
      renameSeriesDialog = new javax.swing.JDialog();
      renameTextBox = new javax.swing.JTextField();
      jLabel39 = new javax.swing.JLabel();
      jLabel40 = new javax.swing.JLabel();
      jLabel41 = new javax.swing.JLabel();
      oldSeriesIDLabel = new javax.swing.JLabel();
      newSeriesIDTextField = new javax.swing.JTextField();
      deleteSeriesDialog = new javax.swing.JDialog();
      jLabel42 = new javax.swing.JLabel();
      jLabel43 = new javax.swing.JLabel();
      deleteSeriesBeginTextBox = new javax.swing.JTextField();
      deleteSeriesEndTextBox = new javax.swing.JTextField();
      moveSeriesDialog = new javax.swing.JDialog();
      jLabel44 = new javax.swing.JLabel();
      jLabel45 = new javax.swing.JLabel();
      seriesMoveToTextBox = new javax.swing.JTextField();
      moveWhichSeriesTextBox = new javax.swing.JTextField();
      sortSeriesDialog = new javax.swing.JDialog();
      sortDataBtn = new javax.swing.JButton();
      sortSeriesQuitBtn = new javax.swing.JButton();
      jLabel46 = new javax.swing.JLabel();
      sortSeriesStatusLabel = new javax.swing.JLabel();
      jScrollPane3 = new javax.swing.JScrollPane();
      sortSeriesList = new javax.swing.JList();
      mergeDataSetDialog = new javax.swing.JDialog();
      jLabel47 = new javax.swing.JLabel();
      mergeChoose2FileBtn = new javax.swing.JButton();
      jLabel48 = new javax.swing.JLabel();
      mergeChoose1FileBtn = new javax.swing.JButton();
      jLabel49 = new javax.swing.JLabel();
      jLabel50 = new javax.swing.JLabel();
      outputFileTextBox = new javax.swing.JTextField();
      jScrollPane2 = new javax.swing.JScrollPane();
      retrieveInfoList = new javax.swing.JList();
      mergeDataBtn = new javax.swing.JButton();
      mergeQuitBtn = new javax.swing.JButton();
      enterFireHistoryDialog = new javax.swing.JDialog();
      utilBtn = new javax.swing.JButton();
      newDataBtn = new javax.swing.JButton();
      importBtn = new javax.swing.JButton();
      changeSettingBtn = new javax.swing.JButton();
      fileNameTextField = new javax.swing.JTextField();
      sampleIDTextField = new javax.swing.JTextField();
      beginYearTextField = new javax.swing.JTextField();
      fireHistoryBtn = new javax.swing.JButton();
      siteInfoBtn = new javax.swing.JButton();
      saveBtn = new javax.swing.JButton();

      dataSetDialog.setAlwaysOnTop(true);
      dataSetDialog.setMinimumSize(new java.awt.Dimension(200, 400));
      dataSetDialog.setModal(true);
      dataSetDialog.setPreferredSize(new java.awt.Dimension(200, 400));
      dataSetDialog.setResizable(false);
      dataSetDialog.getContentPane().setLayout(null);

      jLabel1.setText("First year of the data set");
      dataSetDialog.getContentPane().add(jLabel1);
      jLabel1.setBounds(20, 60, 121, 14);

      jLabel2.setText("Last year of the data set");
      dataSetDialog.getContentPane().add(jLabel2);
      jLabel2.setBounds(20, 120, 120, 14);

      jLabel3.setText("Number of Samples");
      dataSetDialog.getContentPane().add(jLabel3);
      jLabel3.setBounds(20, 180, 92, 14);

      jLabel4.setText("Sample ID length");
      dataSetDialog.getContentPane().add(jLabel4);
      jLabel4.setBounds(20, 240, 81, 14);
      dataSetDialog.getContentPane().add(firstYearTextField);
      firstYearTextField.setBounds(20, 80, 120, 20);
      dataSetDialog.getContentPane().add(sampleIDLengthTextField);
      sampleIDLengthTextField.setBounds(20, 260, 120, 20);
      dataSetDialog.getContentPane().add(lastYearTextField1);
      lastYearTextField1.setBounds(20, 140, 120, 20);

      numberOfSamplesTextField.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            numberOfSamplesTextFieldActionPerformed(evt);
         }
      });
      dataSetDialog.getContentPane().add(numberOfSamplesTextField);
      numberOfSamplesTextField.setBounds(20, 200, 120, 20);

      cancelBtn.setText("Cancel");
      dataSetDialog.getContentPane().add(cancelBtn);
      cancelBtn.setBounds(20, 340, 90, 30);

      saveDataSetBtn1.setText("Save");
      dataSetDialog.getContentPane().add(saveDataSetBtn1);
      saveDataSetBtn1.setBounds(20, 300, 90, 30);

      dataSetDialogLabel.setText("Setup New Data Set");
      dataSetDialog.getContentPane().add(dataSetDialogLabel);
      dataSetDialogLabel.setBounds(20, 20, 140, 14);

      siteInfoDialog.setMinimumSize(new java.awt.Dimension(700, 550));
      siteInfoDialog.setModal(true);
      siteInfoDialog.setPreferredSize(new java.awt.Dimension(700, 550));
      siteInfoDialog.setResizable(false);
      siteInfoDialog.getContentPane().setLayout(null);

      jLabel6.setText("Name of Site");
      siteInfoDialog.getContentPane().add(jLabel6);
      jLabel6.setBounds(10, 10, 90, 14);
      siteInfoDialog.getContentPane().add(jTextField1);
      jTextField1.setBounds(10, 30, 160, 20);

      jLabel7.setText("Site Code");
      siteInfoDialog.getContentPane().add(jLabel7);
      jLabel7.setBounds(10, 60, 90, 14);
      siteInfoDialog.getContentPane().add(jTextField2);
      jTextField2.setBounds(10, 80, 160, 20);

      jLabel8.setText("Collection Date");
      siteInfoDialog.getContentPane().add(jLabel8);
      jLabel8.setBounds(50, 110, 90, 14);
      siteInfoDialog.getContentPane().add(jTextField3);
      jTextField3.setBounds(20, 150, 50, 20);

      jLabel5.setText("Start Year");
      siteInfoDialog.getContentPane().add(jLabel5);
      jLabel5.setBounds(20, 130, 60, 14);
      siteInfoDialog.getContentPane().add(jTextField4);
      jTextField4.setBounds(110, 150, 50, 20);

      jLabel9.setText("End Year");
      siteInfoDialog.getContentPane().add(jLabel9);
      jLabel9.setBounds(110, 130, 60, 14);

      jLabel10.setText("Collectors");
      siteInfoDialog.getContentPane().add(jLabel10);
      jLabel10.setBounds(10, 180, 90, 14);
      siteInfoDialog.getContentPane().add(jTextField5);
      jTextField5.setBounds(10, 200, 350, 20);

      jLabel11.setText("CrossDaters");
      siteInfoDialog.getContentPane().add(jLabel11);
      jLabel11.setBounds(10, 230, 90, 14);
      siteInfoDialog.getContentPane().add(jTextField6);
      jTextField6.setBounds(10, 250, 350, 20);

      jLabel12.setText("Number Samples");
      siteInfoDialog.getContentPane().add(jLabel12);
      jLabel12.setBounds(10, 280, 90, 14);
      siteInfoDialog.getContentPane().add(jTextField7);
      jTextField7.setBounds(10, 300, 160, 20);

      jLabel13.setText("Species Name");
      siteInfoDialog.getContentPane().add(jLabel13);
      jLabel13.setBounds(10, 330, 90, 14);
      siteInfoDialog.getContentPane().add(jTextField8);
      jTextField8.setBounds(10, 350, 160, 20);

      jLabel14.setText("Common Name");
      siteInfoDialog.getContentPane().add(jLabel14);
      jLabel14.setBounds(10, 380, 90, 14);
      siteInfoDialog.getContentPane().add(jTextField9);
      jTextField9.setBounds(10, 400, 160, 20);

      jLabel15.setText("Habitat Type");
      siteInfoDialog.getContentPane().add(jLabel15);
      jLabel15.setBounds(10, 430, 90, 14);
      siteInfoDialog.getContentPane().add(jTextField10);
      jTextField10.setBounds(10, 450, 160, 20);

      jLabel16.setText("Country");
      siteInfoDialog.getContentPane().add(jLabel16);
      jLabel16.setBounds(180, 280, 90, 14);
      siteInfoDialog.getContentPane().add(jTextField11);
      jTextField11.setBounds(180, 300, 160, 20);

      jLabel17.setText("State");
      siteInfoDialog.getContentPane().add(jLabel17);
      jLabel17.setBounds(180, 330, 90, 14);
      siteInfoDialog.getContentPane().add(jTextField12);
      jTextField12.setBounds(180, 350, 160, 20);

      jLabel18.setText("County");
      siteInfoDialog.getContentPane().add(jLabel18);
      jLabel18.setBounds(180, 380, 90, 14);
      siteInfoDialog.getContentPane().add(jTextField13);
      jTextField13.setBounds(180, 400, 160, 20);

      jLabel19.setText("Park/Monument");
      siteInfoDialog.getContentPane().add(jLabel19);
      jLabel19.setBounds(190, 10, 90, 14);
      siteInfoDialog.getContentPane().add(jTextField14);
      jTextField14.setBounds(190, 30, 260, 20);

      jLabel20.setText("National Forest");
      siteInfoDialog.getContentPane().add(jLabel20);
      jLabel20.setBounds(190, 60, 90, 14);
      siteInfoDialog.getContentPane().add(jTextField15);
      jTextField15.setBounds(190, 80, 260, 20);

      jLabel21.setText("Ranger District");
      siteInfoDialog.getContentPane().add(jLabel21);
      jLabel21.setBounds(190, 110, 90, 14);
      siteInfoDialog.getContentPane().add(jTextField16);
      jTextField16.setBounds(190, 130, 260, 20);

      jLabel22.setText("Township");
      siteInfoDialog.getContentPane().add(jLabel22);
      jLabel22.setBounds(350, 280, 90, 14);
      siteInfoDialog.getContentPane().add(jTextField17);
      jTextField17.setBounds(350, 300, 160, 20);

      jLabel23.setText("Range");
      siteInfoDialog.getContentPane().add(jLabel23);
      jLabel23.setBounds(350, 330, 90, 14);
      siteInfoDialog.getContentPane().add(jTextField18);
      jTextField18.setBounds(350, 350, 160, 20);

      jLabel24.setText("Section");
      siteInfoDialog.getContentPane().add(jLabel24);
      jLabel24.setBounds(350, 380, 90, 14);
      siteInfoDialog.getContentPane().add(jTextField19);
      jTextField19.setBounds(350, 400, 160, 20);

      jLabel25.setText("Quarter Section");
      siteInfoDialog.getContentPane().add(jLabel25);
      jLabel25.setBounds(350, 430, 90, 14);
      siteInfoDialog.getContentPane().add(jTextField20);
      jTextField20.setBounds(350, 450, 160, 20);

      jLabel26.setText("UTM easting");
      siteInfoDialog.getContentPane().add(jLabel26);
      jLabel26.setBounds(380, 180, 90, 14);
      siteInfoDialog.getContentPane().add(jTextField21);
      jTextField21.setBounds(380, 200, 160, 20);

      jLabel27.setText("UTM northing");
      siteInfoDialog.getContentPane().add(jLabel27);
      jLabel27.setBounds(380, 230, 90, 14);
      siteInfoDialog.getContentPane().add(jTextField22);
      jTextField22.setBounds(380, 250, 160, 20);

      jLabel28.setText("Latitude");
      siteInfoDialog.getContentPane().add(jLabel28);
      jLabel28.setBounds(470, 10, 90, 14);
      siteInfoDialog.getContentPane().add(jTextField23);
      jTextField23.setBounds(470, 30, 160, 20);

      jLabel29.setText("Longtitude");
      siteInfoDialog.getContentPane().add(jLabel29);
      jLabel29.setBounds(470, 60, 90, 14);
      siteInfoDialog.getContentPane().add(jTextField24);
      jTextField24.setBounds(470, 80, 160, 20);

      jLabel30.setText("Topographic Map");
      siteInfoDialog.getContentPane().add(jLabel30);
      jLabel30.setBounds(470, 110, 90, 14);
      siteInfoDialog.getContentPane().add(jTextField25);
      jTextField25.setBounds(470, 130, 160, 20);
      siteInfoDialog.getContentPane().add(jTextField26);
      jTextField26.setBounds(560, 200, 50, 20);

      jLabel31.setText("Lowest Elev.");
      siteInfoDialog.getContentPane().add(jLabel31);
      jLabel31.setBounds(560, 180, 80, 14);
      siteInfoDialog.getContentPane().add(jTextField27);
      jTextField27.setBounds(560, 250, 50, 20);

      jLabel32.setText("Highest Elev.");
      siteInfoDialog.getContentPane().add(jLabel32);
      jLabel32.setBounds(560, 230, 80, 14);
      siteInfoDialog.getContentPane().add(jTextField28);
      jTextField28.setBounds(560, 300, 50, 20);

      jLabel33.setText("Slope");
      siteInfoDialog.getContentPane().add(jLabel33);
      jLabel33.setBounds(560, 280, 80, 14);
      siteInfoDialog.getContentPane().add(jTextField29);
      jTextField29.setBounds(560, 350, 50, 20);

      jLabel34.setText("Aspect");
      siteInfoDialog.getContentPane().add(jLabel34);
      jLabel34.setBounds(560, 330, 80, 14);

      jLabel35.setText("Area Sampled");
      siteInfoDialog.getContentPane().add(jLabel35);
      jLabel35.setBounds(180, 430, 90, 14);
      siteInfoDialog.getContentPane().add(jTextField30);
      jTextField30.setBounds(180, 450, 160, 20);

      jLabel36.setText("Substrate Type");
      siteInfoDialog.getContentPane().add(jLabel36);
      jLabel36.setBounds(10, 480, 90, 14);
      siteInfoDialog.getContentPane().add(jTextField31);
      jTextField31.setBounds(10, 500, 350, 20);

      jButton1.setText("Cancel");
      siteInfoDialog.getContentPane().add(jButton1);
      jButton1.setBounds(550, 460, 70, 23);

      jButton2.setText("Save");
      siteInfoDialog.getContentPane().add(jButton2);
      jButton2.setBounds(550, 430, 70, 23);

      utilitiesDialog.getContentPane().setLayout(null);

      showSeriesBtn.setText("Show Series");
      showSeriesBtn.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            showSeriesBtnActionPerformed(evt);
         }
      });
      utilitiesDialog.getContentPane().add(showSeriesBtn);
      showSeriesBtn.setBounds(10, 11, 91, 23);

      insertSeriesBtn.setText("Insert Series");
      insertSeriesBtn.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            insertSeriesBtnActionPerformed(evt);
         }
      });
      utilitiesDialog.getContentPane().add(insertSeriesBtn);
      insertSeriesBtn.setBounds(10, 52, 93, 23);

      renameSeriesBtn.setText("Rename Series");
      renameSeriesBtn.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            renameSeriesBtnActionPerformed(evt);
         }
      });
      utilitiesDialog.getContentPane().add(renameSeriesBtn);
      renameSeriesBtn.setBounds(10, 93, 103, 23);

      deleteSeriesBtn.setText("Delete Series");
      deleteSeriesBtn.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            deleteSeriesBtnActionPerformed(evt);
         }
      });
      utilitiesDialog.getContentPane().add(deleteSeriesBtn);
      deleteSeriesBtn.setBounds(10, 134, 95, 23);

      moveSeriesBtn.setText("Move Series");
      moveSeriesBtn.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            moveSeriesBtnActionPerformed(evt);
         }
      });
      utilitiesDialog.getContentPane().add(moveSeriesBtn);
      moveSeriesBtn.setBounds(10, 175, 91, 23);

      sortSeriesBtn.setText("Sort Series");
      sortSeriesBtn.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            sortSeriesBtnActionPerformed(evt);
         }
      });
      utilitiesDialog.getContentPane().add(sortSeriesBtn);
      sortSeriesBtn.setBounds(10, 216, 85, 23);

      mergeDataSetsBtn.setText("Merge two data sets");
      mergeDataSetsBtn.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            mergeDataSetsBtnActionPerformed(evt);
         }
      });
      utilitiesDialog.getContentPane().add(mergeDataSetsBtn);
      mergeDataSetsBtn.setBounds(10, 250, 131, 23);

      quitBtn.setText("Quit");
      utilitiesDialog.getContentPane().add(quitBtn);
      quitBtn.setBounds(10, 290, 53, 23);

      showSeriesDialog.getContentPane().setLayout(null);

      jList1.setModel(new javax.swing.AbstractListModel()
      {
         String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
         public int getSize() { return strings.length; }
         public Object getElementAt(int i) { return strings[i]; }
      });
      jScrollPane1.setViewportView(jList1);

      showSeriesDialog.getContentPane().add(jScrollPane1);
      jScrollPane1.setBounds(90, 20, 80, 280);

      jLabel37.setText("Series");
      showSeriesDialog.getContentPane().add(jLabel37);
      jLabel37.setBounds(110, 0, 29, 14);

      insertDialog.getContentPane().setLayout(null);

      jLabel38.setText("Insert at which series number: ");
      insertDialog.getContentPane().add(jLabel38);
      jLabel38.setBounds(0, 0, 160, 14);
      insertDialog.getContentPane().add(insertSeriesTextField);
      insertSeriesTextField.setBounds(160, 0, 6, 20);

      renameSeriesDialog.getContentPane().setLayout(null);
      renameSeriesDialog.getContentPane().add(renameTextBox);
      renameTextBox.setBounds(230, 0, 170, 20);

      jLabel39.setText("Rename which series number: ");
      renameSeriesDialog.getContentPane().add(jLabel39);
      jLabel39.setBounds(10, 0, 180, 14);

      jLabel40.setText("New Series ID: ");
      renameSeriesDialog.getContentPane().add(jLabel40);
      jLabel40.setBounds(10, 80, 110, 14);

      jLabel41.setText("Old Series ID: ");
      renameSeriesDialog.getContentPane().add(jLabel41);
      jLabel41.setBounds(10, 50, 110, 20);

      oldSeriesIDLabel.setText("xxxxx");
      renameSeriesDialog.getContentPane().add(oldSeriesIDLabel);
      oldSeriesIDLabel.setBounds(220, 60, 30, 14);
      renameSeriesDialog.getContentPane().add(newSeriesIDTextField);
      newSeriesIDTextField.setBounds(220, 80, 6, 20);

      deleteSeriesDialog.getContentPane().setLayout(null);

      jLabel42.setText("Delete from series number:");
      deleteSeriesDialog.getContentPane().add(jLabel42);
      jLabel42.setBounds(20, 30, 150, 20);

      jLabel43.setText("to series number:");
      deleteSeriesDialog.getContentPane().add(jLabel43);
      jLabel43.setBounds(70, 60, 90, 14);
      deleteSeriesDialog.getContentPane().add(deleteSeriesBeginTextBox);
      deleteSeriesBeginTextBox.setBounds(200, 30, 6, 20);
      deleteSeriesDialog.getContentPane().add(deleteSeriesEndTextBox);
      deleteSeriesEndTextBox.setBounds(200, 60, 6, 20);

      moveSeriesDialog.getContentPane().setLayout(null);

      jLabel44.setText("Move which series number: ");
      moveSeriesDialog.getContentPane().add(jLabel44);
      jLabel44.setBounds(0, 0, 150, 14);

      jLabel45.setText("To which series position: ");
      moveSeriesDialog.getContentPane().add(jLabel45);
      jLabel45.setBounds(0, 30, 140, 14);
      moveSeriesDialog.getContentPane().add(seriesMoveToTextBox);
      seriesMoveToTextBox.setBounds(220, 30, 90, 20);
      moveSeriesDialog.getContentPane().add(moveWhichSeriesTextBox);
      moveWhichSeriesTextBox.setBounds(220, 0, 100, 20);

      sortSeriesDialog.getContentPane().setLayout(null);

      sortDataBtn.setText("Sort Data");
      sortSeriesDialog.getContentPane().add(sortDataBtn);
      sortDataBtn.setBounds(10, 240, 100, 23);

      sortSeriesQuitBtn.setText("Quit");
      sortSeriesDialog.getContentPane().add(sortSeriesQuitBtn);
      sortSeriesQuitBtn.setBounds(10, 270, 53, 23);

      jLabel46.setText("Status :");
      sortSeriesDialog.getContentPane().add(jLabel46);
      jLabel46.setBounds(20, 300, 38, 14);

      sortSeriesStatusLabel.setText("xxxxx");
      sortSeriesDialog.getContentPane().add(sortSeriesStatusLabel);
      sortSeriesStatusLabel.setBounds(100, 300, 30, 14);

      sortSeriesList.setModel(new javax.swing.AbstractListModel()
      {
         String[] strings = { "Inside year : Ascending", "Inside year : Descending", "Outside year : Ascending", "Outside year : Descending", " ", "Inside fire : Ascending", "Inside fire : descending", "Outside fire : Ascending", "Outside fire : descending", " ", "By Sample ID" };
         public int getSize() { return strings.length; }
         public Object getElementAt(int i) { return strings[i]; }
      });
      jScrollPane3.setViewportView(sortSeriesList);

      sortSeriesDialog.getContentPane().add(jScrollPane3);
      jScrollPane3.setBounds(10, 10, 170, 220);

      mergeDataSetDialog.getContentPane().setLayout(null);

      jLabel47.setText("First data set to merge: ");
      mergeDataSetDialog.getContentPane().add(jLabel47);
      jLabel47.setBounds(10, 10, 140, 14);

      mergeChoose2FileBtn.setText("choose file");
      mergeChoose2FileBtn.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            mergeChoose2FileBtnActionPerformed(evt);
         }
      });
      mergeDataSetDialog.getContentPane().add(mergeChoose2FileBtn);
      mergeChoose2FileBtn.setBounds(160, 60, 100, 23);

      jLabel48.setText("Second data set to merge: ");
      mergeDataSetDialog.getContentPane().add(jLabel48);
      jLabel48.setBounds(10, 60, 150, 14);

      mergeChoose1FileBtn.setText("choose file");
      mergeChoose1FileBtn.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            mergeChoose1FileBtnActionPerformed(evt);
         }
      });
      mergeDataSetDialog.getContentPane().add(mergeChoose1FileBtn);
      mergeChoose1FileBtn.setBounds(160, 10, 100, 23);

      jLabel49.setText("Output file for merged matrix : ");
      mergeDataSetDialog.getContentPane().add(jLabel49);
      jLabel49.setBounds(10, 120, 170, 14);

      jLabel50.setText("Retrieve Site info from: ");
      mergeDataSetDialog.getContentPane().add(jLabel50);
      jLabel50.setBounds(10, 180, 150, 14);
      mergeDataSetDialog.getContentPane().add(outputFileTextBox);
      outputFileTextBox.setBounds(190, 120, 90, 20);

      retrieveInfoList.setModel(new javax.swing.AbstractListModel()
      {
         String[] strings = { "First", "Second", " " };
         public int getSize() { return strings.length; }
         public Object getElementAt(int i) { return strings[i]; }
      });
      jScrollPane2.setViewportView(retrieveInfoList);

      mergeDataSetDialog.getContentPane().add(jScrollPane2);
      jScrollPane2.setBounds(170, 170, 60, 60);

      mergeDataBtn.setText("Merge data sets");
      mergeDataSetDialog.getContentPane().add(mergeDataBtn);
      mergeDataBtn.setBounds(10, 250, 130, 23);

      mergeQuitBtn.setText("Quit");
      mergeDataSetDialog.getContentPane().add(mergeQuitBtn);
      mergeQuitBtn.setBounds(300, 250, 53, 23);

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setMinimumSize(new java.awt.Dimension(200, 370));
      setPreferredSize(new java.awt.Dimension(200, 370));
      setResizable(false);
      getContentPane().setLayout(null);

      utilBtn.setLabel("Utilities");
      utilBtn.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            utilBtnActionPerformed(evt);
         }
      });
      getContentPane().add(utilBtn);
      utilBtn.setBounds(10, 11, 67, 23);
      utilBtn.getAccessibleContext().setAccessibleName("utilitiesBtn");

      newDataBtn.setText("Set up new data set");
      newDataBtn.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            newDataBtnActionPerformed(evt);
         }
      });
      getContentPane().add(newDataBtn);
      newDataBtn.setBounds(10, 45, 129, 23);
      newDataBtn.getAccessibleContext().setAccessibleName("newDataBtn");

      importBtn.setText("Import Data");
      importBtn.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            importBtnActionPerformed(evt);
         }
      });
      getContentPane().add(importBtn);
      importBtn.setBounds(10, 80, 91, 23);
      importBtn.getAccessibleContext().setAccessibleName("importDataBtn");

      changeSettingBtn.setText("Change settings in data set");
      changeSettingBtn.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            changeSettingBtnActionPerformed(evt);
         }
      });
      getContentPane().add(changeSettingBtn);
      changeSettingBtn.setBounds(10, 115, 165, 23);

      fileNameTextField.setText("Provide a file name here");
      getContentPane().add(fileNameTextField);
      fileNameTextField.setBounds(10, 150, 133, 20);

      sampleIDTextField.setText("Enter sample ID here");
      getContentPane().add(sampleIDTextField);
      sampleIDTextField.setBounds(10, 180, 122, 20);

      beginYearTextField.setText("Enter beginning year here");
      getContentPane().add(beginYearTextField);
      beginYearTextField.setBounds(10, 210, 131, 20);

      fireHistoryBtn.setText("Edit fire history data here");
      fireHistoryBtn.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            fireHistoryBtnActionPerformed(evt);
         }
      });
      getContentPane().add(fireHistoryBtn);
      fireHistoryBtn.setBounds(10, 240, 155, 23);

      siteInfoBtn.setText("Edit site info here");
      siteInfoBtn.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            siteInfoBtnActionPerformed(evt);
         }
      });
      getContentPane().add(siteInfoBtn);
      siteInfoBtn.setBounds(10, 270, 117, 23);

      saveBtn.setText("Save");
      getContentPane().add(saveBtn);
      saveBtn.setBounds(10, 300, 57, 23);

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void utilBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_utilBtnActionPerformed
   {//GEN-HEADEREND:event_utilBtnActionPerformed
      this.utilitiesDialog.setVisible(true);
   }//GEN-LAST:event_utilBtnActionPerformed

   private void newDataBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newDataBtnActionPerformed
   {//GEN-HEADEREND:event_newDataBtnActionPerformed
      dataSetDialogLabel.setText("Set up new data set");
      dataSetDialog.setVisible(true);
   }//GEN-LAST:event_newDataBtnActionPerformed

   private void importBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_importBtnActionPerformed
   {//GEN-HEADEREND:event_importBtnActionPerformed
      this.importDataFileChooser.showOpenDialog(this);
   }//GEN-LAST:event_importBtnActionPerformed

   private void numberOfSamplesTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberOfSamplesTextFieldActionPerformed
   {//GEN-HEADEREND:event_numberOfSamplesTextFieldActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_numberOfSamplesTextFieldActionPerformed

   private void changeSettingBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_changeSettingBtnActionPerformed
   {//GEN-HEADEREND:event_changeSettingBtnActionPerformed
      dataSetDialogLabel.setText("Change settings in data set");
      dataSetDialog.setVisible(true);
   }//GEN-LAST:event_changeSettingBtnActionPerformed

   private void siteInfoBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_siteInfoBtnActionPerformed
   {//GEN-HEADEREND:event_siteInfoBtnActionPerformed
      this.siteInfoDialog.setVisible(true);
   }//GEN-LAST:event_siteInfoBtnActionPerformed

   private void showSeriesBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_showSeriesBtnActionPerformed
   {//GEN-HEADEREND:event_showSeriesBtnActionPerformed
      this.showSeriesDialog.setVisible(true);
   }//GEN-LAST:event_showSeriesBtnActionPerformed

   private void insertSeriesBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_insertSeriesBtnActionPerformed
   {//GEN-HEADEREND:event_insertSeriesBtnActionPerformed
      this.insertDialog.setVisible(true);
   }//GEN-LAST:event_insertSeriesBtnActionPerformed

   private void renameSeriesBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_renameSeriesBtnActionPerformed
   {//GEN-HEADEREND:event_renameSeriesBtnActionPerformed
      this.renameSeriesDialog.setVisible(true);
   }//GEN-LAST:event_renameSeriesBtnActionPerformed

   private void deleteSeriesBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_deleteSeriesBtnActionPerformed
   {//GEN-HEADEREND:event_deleteSeriesBtnActionPerformed
      deleteSeriesDialog.setVisible(true);
   }//GEN-LAST:event_deleteSeriesBtnActionPerformed

   private void moveSeriesBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_moveSeriesBtnActionPerformed
   {//GEN-HEADEREND:event_moveSeriesBtnActionPerformed
      this.moveSeriesBtn.setVisible(true);
   }//GEN-LAST:event_moveSeriesBtnActionPerformed

   private void sortSeriesBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sortSeriesBtnActionPerformed
   {//GEN-HEADEREND:event_sortSeriesBtnActionPerformed
      sortSeriesDialog.setVisible(true);
   }//GEN-LAST:event_sortSeriesBtnActionPerformed

   private void mergeDataSetsBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mergeDataSetsBtnActionPerformed
   {//GEN-HEADEREND:event_mergeDataSetsBtnActionPerformed
      this.mergeDataSetDialog.setVisible(true);
   }//GEN-LAST:event_mergeDataSetsBtnActionPerformed

   private void mergeChoose2FileBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mergeChoose2FileBtnActionPerformed
   {//GEN-HEADEREND:event_mergeChoose2FileBtnActionPerformed
      this.importDataFileChooser.setVisible(true);
   }//GEN-LAST:event_mergeChoose2FileBtnActionPerformed

   private void mergeChoose1FileBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mergeChoose1FileBtnActionPerformed
   {//GEN-HEADEREND:event_mergeChoose1FileBtnActionPerformed
      this.importDataFileChooser.setVisible(true);
   }//GEN-LAST:event_mergeChoose1FileBtnActionPerformed

   private void fireHistoryBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fireHistoryBtnActionPerformed
   {//GEN-HEADEREND:event_fireHistoryBtnActionPerformed
      this.enterFireHistoryDialog.setVisible(true);
   }//GEN-LAST:event_fireHistoryBtnActionPerformed

   /**
    @param args the command line arguments
    */
   public static void main(String args[])
   {
      /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try
      {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
         {
            if ("Nimbus".equals(info.getName()))
            {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      }
      catch (ClassNotFoundException ex)
      {
         java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (InstantiationException ex)
      {
         java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (IllegalAccessException ex)
      {
         java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (javax.swing.UnsupportedLookAndFeelException ex)
      {
         java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
        //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new NewJFrame().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JTextField beginYearTextField;
   private javax.swing.JButton cancelBtn;
   private javax.swing.JButton changeSettingBtn;
   private javax.swing.JDialog dataSetDialog;
   private javax.swing.JLabel dataSetDialogLabel;
   private javax.swing.JTextField deleteSeriesBeginTextBox;
   private javax.swing.JButton deleteSeriesBtn;
   private javax.swing.JDialog deleteSeriesDialog;
   private javax.swing.JTextField deleteSeriesEndTextBox;
   private javax.swing.JDialog enterFireHistoryDialog;
   private javax.swing.JDialog errorDialog;
   private javax.swing.JTextField fileNameTextField;
   private javax.swing.JButton fireHistoryBtn;
   private javax.swing.JTextField firstYearTextField;
   private javax.swing.JButton importBtn;
   private javax.swing.JFileChooser importDataFileChooser;
   private javax.swing.JDialog insertDialog;
   private javax.swing.JButton insertSeriesBtn;
   private javax.swing.JTextField insertSeriesTextField;
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel10;
   private javax.swing.JLabel jLabel11;
   private javax.swing.JLabel jLabel12;
   private javax.swing.JLabel jLabel13;
   private javax.swing.JLabel jLabel14;
   private javax.swing.JLabel jLabel15;
   private javax.swing.JLabel jLabel16;
   private javax.swing.JLabel jLabel17;
   private javax.swing.JLabel jLabel18;
   private javax.swing.JLabel jLabel19;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel20;
   private javax.swing.JLabel jLabel21;
   private javax.swing.JLabel jLabel22;
   private javax.swing.JLabel jLabel23;
   private javax.swing.JLabel jLabel24;
   private javax.swing.JLabel jLabel25;
   private javax.swing.JLabel jLabel26;
   private javax.swing.JLabel jLabel27;
   private javax.swing.JLabel jLabel28;
   private javax.swing.JLabel jLabel29;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel30;
   private javax.swing.JLabel jLabel31;
   private javax.swing.JLabel jLabel32;
   private javax.swing.JLabel jLabel33;
   private javax.swing.JLabel jLabel34;
   private javax.swing.JLabel jLabel35;
   private javax.swing.JLabel jLabel36;
   private javax.swing.JLabel jLabel37;
   private javax.swing.JLabel jLabel38;
   private javax.swing.JLabel jLabel39;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel40;
   private javax.swing.JLabel jLabel41;
   private javax.swing.JLabel jLabel42;
   private javax.swing.JLabel jLabel43;
   private javax.swing.JLabel jLabel44;
   private javax.swing.JLabel jLabel45;
   private javax.swing.JLabel jLabel46;
   private javax.swing.JLabel jLabel47;
   private javax.swing.JLabel jLabel48;
   private javax.swing.JLabel jLabel49;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel50;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JList jList1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JScrollPane jScrollPane3;
   private javax.swing.JTextField jTextField1;
   private javax.swing.JTextField jTextField10;
   private javax.swing.JTextField jTextField11;
   private javax.swing.JTextField jTextField12;
   private javax.swing.JTextField jTextField13;
   private javax.swing.JTextField jTextField14;
   private javax.swing.JTextField jTextField15;
   private javax.swing.JTextField jTextField16;
   private javax.swing.JTextField jTextField17;
   private javax.swing.JTextField jTextField18;
   private javax.swing.JTextField jTextField19;
   private javax.swing.JTextField jTextField2;
   private javax.swing.JTextField jTextField20;
   private javax.swing.JTextField jTextField21;
   private javax.swing.JTextField jTextField22;
   private javax.swing.JTextField jTextField23;
   private javax.swing.JTextField jTextField24;
   private javax.swing.JTextField jTextField25;
   private javax.swing.JTextField jTextField26;
   private javax.swing.JTextField jTextField27;
   private javax.swing.JTextField jTextField28;
   private javax.swing.JTextField jTextField29;
   private javax.swing.JTextField jTextField3;
   private javax.swing.JTextField jTextField30;
   private javax.swing.JTextField jTextField31;
   private javax.swing.JTextField jTextField4;
   private javax.swing.JTextField jTextField5;
   private javax.swing.JTextField jTextField6;
   private javax.swing.JTextField jTextField7;
   private javax.swing.JTextField jTextField8;
   private javax.swing.JTextField jTextField9;
   private javax.swing.JTextField lastYearTextField1;
   private javax.swing.JButton mergeChoose1FileBtn;
   private javax.swing.JButton mergeChoose2FileBtn;
   private javax.swing.JButton mergeDataBtn;
   private javax.swing.JDialog mergeDataSetDialog;
   private javax.swing.JButton mergeDataSetsBtn;
   private javax.swing.JButton mergeQuitBtn;
   private javax.swing.JButton moveSeriesBtn;
   private javax.swing.JDialog moveSeriesDialog;
   private javax.swing.JTextField moveWhichSeriesTextBox;
   private javax.swing.JButton newDataBtn;
   private javax.swing.JTextField newSeriesIDTextField;
   private javax.swing.JTextField numberOfSamplesTextField;
   private javax.swing.JLabel oldSeriesIDLabel;
   private javax.swing.JTextField outputFileTextBox;
   private javax.swing.JButton quitBtn;
   private javax.swing.JButton renameSeriesBtn;
   private javax.swing.JDialog renameSeriesDialog;
   private javax.swing.JTextField renameTextBox;
   private javax.swing.JList retrieveInfoList;
   private javax.swing.JTextField sampleIDLengthTextField;
   private javax.swing.JTextField sampleIDTextField;
   private javax.swing.JButton saveBtn;
   private javax.swing.JButton saveDataSetBtn1;
   private javax.swing.JTextField seriesMoveToTextBox;
   private javax.swing.JButton showSeriesBtn;
   private javax.swing.JDialog showSeriesDialog;
   private javax.swing.JButton siteInfoBtn;
   private javax.swing.JDialog siteInfoDialog;
   private javax.swing.JButton sortDataBtn;
   private javax.swing.JButton sortSeriesBtn;
   private javax.swing.JDialog sortSeriesDialog;
   private javax.swing.JList sortSeriesList;
   private javax.swing.JButton sortSeriesQuitBtn;
   private javax.swing.JLabel sortSeriesStatusLabel;
   private javax.swing.JButton utilBtn;
   private javax.swing.JDialog utilitiesDialog;
   // End of variables declaration//GEN-END:variables
}
