/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se3860_secondgui;

import java.awt.event.ActionEvent;
import java.io.File;
import java.util.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Nathan
 */
public class HomeGui extends javax.swing.JFrame
{
   private String[] siteInfo;
   private String fileName;
   int startDate, endDate, sampleNum, IDlen;
   char sampleId[][];
   char dataInfo[][];
   boolean fileLoaded = false;
   DataHelper d = new DataHelper();
   
   public HomeGui()
   {
        initComponents();
        errorlbl2.setVisible(false);
        errorlbl1.setVisible(false);
        errorlbl3.setVisible(false);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      jTabbedPane1 = new javax.swing.JTabbedPane();
      homePanel = new javax.swing.JPanel();
      jLabel72 = new javax.swing.JLabel();
      jScrollPane3 = new javax.swing.JScrollPane();
      jTextArea2 = new javax.swing.JTextArea();
      dataSettingsPanel = new javax.swing.JPanel();
      jLabel67 = new javax.swing.JLabel();
      txtFirstYear = new javax.swing.JTextField();
      txtSampleIDLength = new javax.swing.JTextField();
      txtLastYear = new javax.swing.JTextField();
      txtNumberOfSamples = new javax.swing.JTextField();
      saveDataSetBtn1 = new javax.swing.JButton();
      jLabel68 = new javax.swing.JLabel();
      jLabel69 = new javax.swing.JLabel();
      jLabel70 = new javax.swing.JLabel();
      txtFileName = new javax.swing.JTextField();
      jLabel71 = new javax.swing.JLabel();
      saveDataSetBtn2 = new javax.swing.JButton();
      resetAllFieldsData = new javax.swing.JButton();
      jLabel65 = new javax.swing.JLabel();
      jLabel66 = new javax.swing.JLabel();
      jSeparator4 = new javax.swing.JSeparator();
      jScrollPane4 = new javax.swing.JScrollPane();
      jTextArea3 = new javax.swing.JTextArea();
      siteInfoPanel = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      txtSiteName = new javax.swing.JTextField();
      jLabel2 = new javax.swing.JLabel();
      txtParkMonument = new javax.swing.JTextField();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      txtSiteCode = new javax.swing.JTextField();
      jLabel5 = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      txtNationalForest = new javax.swing.JTextField();
      jLabel7 = new javax.swing.JLabel();
      jLabel8 = new javax.swing.JLabel();
      txtRangerDistrict = new javax.swing.JTextField();
      jLabel9 = new javax.swing.JLabel();
      jLabel10 = new javax.swing.JLabel();
      txtTopographicMap = new javax.swing.JTextField();
      jLabel11 = new javax.swing.JLabel();
      jLabel12 = new javax.swing.JLabel();
      txtCollectors = new javax.swing.JTextField();
      jLabel13 = new javax.swing.JLabel();
      jLabel14 = new javax.swing.JLabel();
      txtState = new javax.swing.JTextField();
      jLabel15 = new javax.swing.JLabel();
      jLabel16 = new javax.swing.JLabel();
      txtSpeciesName = new javax.swing.JTextField();
      jLabel17 = new javax.swing.JLabel();
      jLabel18 = new javax.swing.JLabel();
      txtTownship = new javax.swing.JTextField();
      jLabel19 = new javax.swing.JLabel();
      jLabel20 = new javax.swing.JLabel();
      txtCountry = new javax.swing.JTextField();
      jLabel21 = new javax.swing.JLabel();
      jLabel22 = new javax.swing.JLabel();
      txtNumSamples = new javax.swing.JTextField();
      jLabel23 = new javax.swing.JLabel();
      jLabel24 = new javax.swing.JLabel();
      txtCrossDaters = new javax.swing.JTextField();
      jLabel25 = new javax.swing.JLabel();
      jLabel26 = new javax.swing.JLabel();
      txtQuarterSection = new javax.swing.JTextField();
      jLabel29 = new javax.swing.JLabel();
      jLabel30 = new javax.swing.JLabel();
      txtAreaSampled = new javax.swing.JTextField();
      jLabel31 = new javax.swing.JLabel();
      jLabel32 = new javax.swing.JLabel();
      txtHabitatType = new javax.swing.JTextField();
      jLabel33 = new javax.swing.JLabel();
      jLabel34 = new javax.swing.JLabel();
      txtSection = new javax.swing.JTextField();
      jLabel35 = new javax.swing.JLabel();
      jLabel36 = new javax.swing.JLabel();
      txtCounty = new javax.swing.JTextField();
      jLabel37 = new javax.swing.JLabel();
      jLabel38 = new javax.swing.JLabel();
      txtCommonName = new javax.swing.JTextField();
      jLabel39 = new javax.swing.JLabel();
      jLabel40 = new javax.swing.JLabel();
      txtRange = new javax.swing.JTextField();
      jLabel41 = new javax.swing.JLabel();
      jLabel42 = new javax.swing.JLabel();
      txtUTMNorthing = new javax.swing.JTextField();
      jLabel43 = new javax.swing.JLabel();
      jLabel44 = new javax.swing.JLabel();
      txtUTMEasting = new javax.swing.JTextField();
      jLabel45 = new javax.swing.JLabel();
      jLabel46 = new javax.swing.JLabel();
      txtAspect = new javax.swing.JTextField();
      jLabel47 = new javax.swing.JLabel();
      jLabel48 = new javax.swing.JLabel();
      txtSlope = new javax.swing.JTextField();
      jLabel49 = new javax.swing.JLabel();
      jLabel50 = new javax.swing.JLabel();
      txtHighestElev = new javax.swing.JTextField();
      jLabel51 = new javax.swing.JLabel();
      jLabel52 = new javax.swing.JLabel();
      txtLowestElevation = new javax.swing.JTextField();
      jLabel53 = new javax.swing.JLabel();
      jLabel54 = new javax.swing.JLabel();
      txtSubstrateType = new javax.swing.JTextField();
      jLabel55 = new javax.swing.JLabel();
      jLabel56 = new javax.swing.JLabel();
      txtStartYear = new javax.swing.JTextField();
      jLabel57 = new javax.swing.JLabel();
      jLabel58 = new javax.swing.JLabel();
      txtEndYear = new javax.swing.JTextField();
      jLabel59 = new javax.swing.JLabel();
      jLabel60 = new javax.swing.JLabel();
      txtLatitude = new javax.swing.JTextField();
      jLabel61 = new javax.swing.JLabel();
      jLabel62 = new javax.swing.JLabel();
      txtLongitude = new javax.swing.JTextField();
      jLabel63 = new javax.swing.JLabel();
      jLabel64 = new javax.swing.JLabel();
      btnSave = new javax.swing.JButton();
      btnDeleteAll = new javax.swing.JButton();
      jSeparator1 = new javax.swing.JSeparator();
      jSeparator2 = new javax.swing.JSeparator();
      jSeparator3 = new javax.swing.JSeparator();
      txtCollectionDate = new javax.swing.JTextField();
      jLabel73 = new javax.swing.JLabel();
      jLabel74 = new javax.swing.JLabel();
      resetDataFieldsBtn = new javax.swing.JButton();
      fireHistoryPanel = new javax.swing.JPanel();
      jLabel27 = new javax.swing.JLabel();
      jScrollPane1 = new javax.swing.JScrollPane();
      jTextArea1 = new javax.swing.JTextArea();
      cmbNewValue = new javax.swing.JComboBox();
      jLabel28 = new javax.swing.JLabel();
      btnFillFifty = new javax.swing.JButton();
      txtSampleId = new javax.swing.JTextField();
      btnchangeSampleID = new javax.swing.JButton();
      sampleListDropDown = new javax.swing.JComboBox();
      jScrollPane2 = new javax.swing.JScrollPane();
      fireHistoryTable = new javax.swing.JTable();
      errorlbl1 = new javax.swing.JLabel();
      errorlbl2 = new javax.swing.JLabel();
      errorlbl3 = new javax.swing.JLabel();
      maxSamplesize = new javax.swing.JLabel();
      saveDataBtn = new javax.swing.JButton();
      modifyBtn = new javax.swing.JButton();
      jMenuBar1 = new javax.swing.JMenuBar();
      jMenu1 = new javax.swing.JMenu();
      mnuImportData = new javax.swing.JMenuItem();
      mnuSaveFile = new javax.swing.JMenuItem();
      jMenu2 = new javax.swing.JMenu();
      jMenuItem1 = new javax.swing.JMenuItem();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("FHX2 GUI - SE3860");

      jLabel72.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
      jLabel72.setForeground(new java.awt.Color(255, 0, 0));
      jLabel72.setText("FHX2 GUI: Software for the analysis of Fire history from tree rings");

      jTextArea2.setEditable(false);
      jTextArea2.setBackground(new java.awt.Color(240, 240, 240));
      jTextArea2.setColumns(20);
      jTextArea2.setRows(5);
      jTextArea2.setText("Before editing Fire History for a site, you must first\nenter valid information into the \"Data Settings\" Tab. \nDoing so will populate the Fire History Tab with the\nfunctionality to save and edit Fire History information.");
      jScrollPane3.setViewportView(jTextArea2);

      javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
      homePanel.setLayout(homePanelLayout);
      homePanelLayout.setHorizontalGroup(
         homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(homePanelLayout.createSequentialGroup()
            .addGap(213, 213, 213)
            .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jScrollPane3)
               .addComponent(jLabel72, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(229, Short.MAX_VALUE))
      );
      homePanelLayout.setVerticalGroup(
         homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(homePanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel72)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(579, Short.MAX_VALUE))
      );

      jTabbedPane1.addTab("Home", homePanel);

      dataSettingsPanel.setMaximumSize(new java.awt.Dimension(900, 900));

      jLabel67.setText("Sample ID length");

      saveDataSetBtn1.setText("Save Existing Data Set");
      saveDataSetBtn1.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            saveDataSetBtn1ActionPerformed(evt);
         }
      });

      jLabel68.setText("First year of the data set");

      jLabel69.setText("Last year of the data set");

      jLabel70.setText("Number of Samples");

      txtFileName.addKeyListener(new java.awt.event.KeyAdapter()
      {
         public void keyTyped(java.awt.event.KeyEvent evt)
         {
            txtFileNameKeyTyped(evt);
         }
      });

      jLabel71.setText("New File Name");

      saveDataSetBtn2.setText("Create New Data Set");
      saveDataSetBtn2.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            saveDataSetBtn2ActionPerformed(evt);
         }
      });

      resetAllFieldsData.setText("Reset All Fields");
      resetAllFieldsData.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            resetAllFieldsDataActionPerformed(evt);
         }
      });

      jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel65.setText("Update Existing Data");

      jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel66.setText("Create New Data Set");

      jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

      jTextArea3.setEditable(false);
      jTextArea3.setBackground(new java.awt.Color(240, 240, 240));
      jTextArea3.setColumns(20);
      jTextArea3.setLineWrap(true);
      jTextArea3.setRows(5);
      jTextArea3.setText("Select \"Save Existing Data Set\" if you wish to \nupdate the current fields of the \npreviously created data set.\n\nSelect Create New Data Set to create a new file \nwith the current fields of information.\nNOTE: Creating a new Data Set will reset all \nsample ID's and Sample Data for the given file.");
      jScrollPane4.setViewportView(jTextArea3);

      javax.swing.GroupLayout dataSettingsPanelLayout = new javax.swing.GroupLayout(dataSettingsPanel);
      dataSettingsPanel.setLayout(dataSettingsPanelLayout);
      dataSettingsPanelLayout.setHorizontalGroup(
         dataSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(dataSettingsPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(dataSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(txtSampleIDLength, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(txtNumberOfSamples, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(txtLastYear, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jLabel69, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(txtFirstYear, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jLabel68, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(txtFileName, javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(dataSettingsPanelLayout.createSequentialGroup()
                  .addGroup(dataSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel71)
                     .addComponent(jLabel67)
                     .addComponent(jLabel70)
                     .addGroup(dataSettingsPanelLayout.createSequentialGroup()
                        .addGroup(dataSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(dataSettingsPanelLayout.createSequentialGroup()
                              .addGroup(dataSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                 .addComponent(jLabel65, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                 .addComponent(saveDataSetBtn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                              .addGap(30, 30, 30)
                              .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(dataSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                 .addComponent(saveDataSetBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                 .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                           .addGroup(dataSettingsPanelLayout.createSequentialGroup()
                              .addGap(128, 128, 128)
                              .addComponent(resetAllFieldsData, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGap(0, 22, Short.MAX_VALUE)))
            .addContainerGap())
      );
      dataSettingsPanelLayout.setVerticalGroup(
         dataSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(dataSettingsPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel68)
            .addGap(4, 4, 4)
            .addComponent(txtFirstYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel69)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtLastYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel70)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtNumberOfSamples, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel67)
            .addGap(3, 3, 3)
            .addComponent(txtSampleIDLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel71)
            .addGap(3, 3, 3)
            .addComponent(txtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(dataSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(dataSettingsPanelLayout.createSequentialGroup()
                  .addGap(18, 18, 18)
                  .addGroup(dataSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(dataSettingsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel65)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveDataSetBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(dataSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dataSettingsPanelLayout.createSequentialGroup()
                           .addComponent(jLabel66)
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                           .addComponent(saveDataSetBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataSettingsPanelLayout.createSequentialGroup()
                           .addGap(1, 1, 1)
                           .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(resetAllFieldsData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataSettingsPanelLayout.createSequentialGroup()
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(372, 372, 372))))
      );

      jTabbedPane1.addTab("Data Settings ", dataSettingsPanel);

      jLabel1.setText("Name of Site");

      jLabel2.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel2.setText("* Max 70 Characters");

      jLabel3.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel3.setText("* Max 70 Characters");

      jLabel4.setText("Park/Monument");

      jLabel5.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel5.setText("* Max 70 Characters");

      jLabel6.setText("Site Code");

      jLabel7.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel7.setText("* Max 70 Characters");

      jLabel8.setText("National Forest");

      jLabel9.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel9.setText("* Max 70 Characters");

      jLabel10.setText("Ranger District");

      jLabel11.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel11.setText("* Max 70 Characters");

      jLabel12.setText("Topographic Map");

      jLabel13.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel13.setText("* Max 70 Characters");

      jLabel14.setText("Collectors");

      jLabel15.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel15.setText("* Max 70 Characters");

      jLabel16.setText("State");

      jLabel17.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel17.setText("* Max 70 Characters");

      jLabel18.setText("Species Name");

      jLabel19.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel19.setText("* Max 70 Characters");

      jLabel20.setText("Township");

      jLabel21.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel21.setText("* Max 70 Characters");

      jLabel22.setText("Country");

      jLabel23.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel23.setText("* Max 70 Characters");

      jLabel24.setText("Number of Samples");

      jLabel25.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel25.setText("* Max 70 Characters");

      jLabel26.setText("CrossDaters");

      jLabel29.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel29.setText("* Max 70 Characters");

      jLabel30.setText("Quarter Section");

      jLabel31.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel31.setText("* Max 70 Characters");

      jLabel32.setText("Area Sampled");

      jLabel33.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel33.setText("* Max 70 Characters");

      jLabel34.setText("Habitat Type");

      jLabel35.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel35.setText("* Max 70 Characters");

      jLabel36.setText("Section");

      jLabel37.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel37.setText("* Max 70 Characters");

      jLabel38.setText("County");

      jLabel39.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel39.setText("* Max 70 Characters");

      jLabel40.setText("Common Name");

      jLabel41.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel41.setText("* Max 70 Characters");

      jLabel42.setText("Range");

      jLabel43.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel43.setText("* Max 70 Characters");

      jLabel44.setText("UTM Northing");

      jLabel45.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel45.setText("* Max 70 Characters");

      jLabel46.setText("UTM Easting");

      jLabel47.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel47.setText("* Max 70 Characters");

      jLabel48.setText("Aspect");

      jLabel49.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel49.setText("* Max 70 Characters");

      jLabel50.setText("Slope");

      jLabel51.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel51.setText("* Max 70 Characters");

      jLabel52.setText("Highest Elevation");

      jLabel53.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel53.setText("* Max 70 Characters");

      jLabel54.setText("Lowest Elevation");

      jLabel55.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel55.setText("* Max 70 Characters");

      jLabel56.setText("Substrate Type");

      jLabel57.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel57.setText("* Max 70 Characters");

      jLabel58.setText("Start Year");

      jLabel59.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel59.setText("* Max 70 Characters");

      jLabel60.setText("End Year");

      jLabel61.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel61.setText("* Max 70 Characters");

      jLabel62.setText("Latitude");

      jLabel63.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel63.setText("* Max 70 Characters");

      jLabel64.setText("Longtitude");

      btnSave.setText("Save");
      btnSave.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            btnSaveActionPerformed(evt);
         }
      });

      btnDeleteAll.setText("Delete All");
      btnDeleteAll.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            btnDeleteAllActionPerformed(evt);
         }
      });

      jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
      jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

      jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
      jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

      jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
      jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

      jLabel73.setText("Collection Date");

      jLabel74.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel74.setText("* Max 70 Characters");

      resetDataFieldsBtn.setText("Reset From File");
      resetDataFieldsBtn.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            resetDataFieldsBtnActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout siteInfoPanelLayout = new javax.swing.GroupLayout(siteInfoPanel);
      siteInfoPanel.setLayout(siteInfoPanelLayout);
      siteInfoPanelLayout.setHorizontalGroup(
         siteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(siteInfoPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(siteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel3)
               .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtParkMonument, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel2)
               .addComponent(txtSiteName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtSiteCode, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel7)
               .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtNationalForest, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel9)
               .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtRangerDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel11)
               .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtTopographicMap, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel13)
               .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtCollectors, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel57)
               .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel5))
            .addGap(50, 50, 50)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(50, 50, 50)
            .addGroup(siteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel25)
               .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtCrossDaters, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel23)
               .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtNumSamples, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel21)
               .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel19)
               .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtTownship, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel17)
               .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtSpeciesName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel15)
               .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel59)
               .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtEndYear, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel37)
               .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtCounty, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(50, 50, 50)
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(50, 50, 50)
            .addGroup(siteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel39)
               .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtCommonName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel35)
               .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtSection, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel33)
               .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtHabitatType, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel31)
               .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtAreaSampled, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel29)
               .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtQuarterSection, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel41)
               .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtRange, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel55)
               .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtSubstrateType, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel61)
               .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(50, 50, 50)
            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(50, 50, 50)
            .addGroup(siteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel53)
               .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtLowestElevation, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
               .addComponent(jLabel51)
               .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtHighestElev, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
               .addComponent(jLabel49)
               .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtSlope, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
               .addComponent(jLabel47)
               .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtAspect, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
               .addComponent(jLabel45)
               .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtUTMEasting, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
               .addComponent(jLabel43)
               .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtUTMNorthing, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
               .addComponent(jLabel63)
               .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtLongitude, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
               .addComponent(btnDeleteAll, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
               .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(txtCollectionDate)
               .addComponent(jLabel73)
               .addComponent(jLabel74)
               .addComponent(resetDataFieldsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );
      siteInfoPanelLayout.setVerticalGroup(
         siteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(siteInfoPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(siteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(siteInfoPanelLayout.createSequentialGroup()
                  .addGroup(siteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(0, 148, Short.MAX_VALUE))
               .addGroup(siteInfoPanelLayout.createSequentialGroup()
                  .addGroup(siteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(siteInfoPanelLayout.createSequentialGroup()
                        .addGroup(siteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addGroup(siteInfoPanelLayout.createSequentialGroup()
                              .addComponent(jLabel1)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel2)
                              .addGap(5, 5, 5)
                              .addComponent(txtSiteName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel4)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel3)
                              .addGap(5, 5, 5)
                              .addComponent(txtParkMonument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel6)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel5)
                              .addGap(5, 5, 5)
                              .addComponent(txtSiteCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel8)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel7)
                              .addGap(5, 5, 5)
                              .addComponent(txtNationalForest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel10)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel9)
                              .addGap(5, 5, 5)
                              .addComponent(txtRangerDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel12)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel11)
                              .addGap(5, 5, 5)
                              .addComponent(txtTopographicMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel14)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel13)
                              .addGap(5, 5, 5)
                              .addComponent(txtCollectors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addGroup(siteInfoPanelLayout.createSequentialGroup()
                              .addComponent(jLabel42)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel41)
                              .addGap(5, 5, 5)
                              .addComponent(txtRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel40)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel39)
                              .addGap(5, 5, 5)
                              .addComponent(txtCommonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(7, 7, 7)
                              .addComponent(jLabel36)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel35)
                              .addGap(5, 5, 5)
                              .addComponent(txtSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel34)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel33)
                              .addGap(5, 5, 5)
                              .addComponent(txtHabitatType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel32)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel31)
                              .addGap(5, 5, 5)
                              .addComponent(txtAreaSampled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel30)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel29)
                              .addGap(5, 5, 5)
                              .addComponent(txtQuarterSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel56)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel55)
                              .addGap(5, 5, 5)
                              .addComponent(txtSubstrateType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addGroup(siteInfoPanelLayout.createSequentialGroup()
                              .addComponent(jLabel54)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel53)
                              .addGap(5, 5, 5)
                              .addComponent(txtLowestElevation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel52)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel51)
                              .addGap(5, 5, 5)
                              .addComponent(txtHighestElev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel50)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel49)
                              .addGap(5, 5, 5)
                              .addComponent(txtSlope, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel48)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel47)
                              .addGap(5, 5, 5)
                              .addComponent(txtAspect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel46)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel45)
                              .addGap(5, 5, 5)
                              .addComponent(txtUTMEasting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel44)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel43)
                              .addGap(5, 5, 5)
                              .addComponent(txtUTMNorthing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel64)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel63)
                              .addGap(5, 5, 5)
                              .addComponent(txtLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(siteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addGroup(siteInfoPanelLayout.createSequentialGroup()
                              .addComponent(jLabel58)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel57)
                              .addGap(5, 5, 5)
                              .addComponent(txtStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addGroup(siteInfoPanelLayout.createSequentialGroup()
                              .addComponent(jLabel60)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel59)
                              .addGap(5, 5, 5)
                              .addComponent(txtEndYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addGroup(siteInfoPanelLayout.createSequentialGroup()
                              .addComponent(jLabel62)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel61)
                              .addGap(5, 5, 5)
                              .addComponent(txtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siteInfoPanelLayout.createSequentialGroup()
                              .addComponent(jLabel73)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(jLabel74)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(txtCollectionDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                     .addGroup(siteInfoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addGap(5, 5, 5)
                        .addComponent(txtCrossDaters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addGap(5, 5, 5)
                        .addComponent(txtNumSamples, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addGap(5, 5, 5)
                        .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addGap(5, 5, 5)
                        .addComponent(txtTownship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addGap(5, 5, 5)
                        .addComponent(txtSpeciesName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addGap(5, 5, 5)
                        .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel37)
                        .addGap(5, 5, 5)
                        .addComponent(txtCounty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGap(18, 18, 18)
                  .addComponent(btnSave)
                  .addGap(4, 4, 4)
                  .addComponent(resetDataFieldsBtn)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btnDeleteAll)
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
      );

      jTabbedPane1.addTab("Site Information", siteInfoPanel);

      jLabel27.setText("Please Choose Entry Sample ID:");

      jTextArea1.setEditable(false);
      jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
      jTextArea1.setColumns(20);
      jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
      jTextArea1.setRows(5);
      jTextArea1.setText("To change the value stored for a given year, select  the desired year(s) on the left and then\nchoose a new value from the dropdown box below. Selecting the \"Fill Selected Year(s)\" button will \nautomatically fill all selected year(s) values with the currently selected \"New Value\".");
      jScrollPane1.setViewportView(jTextArea1);

      cmbNewValue.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Null year ( . ) ", "Pith year ( [ )", "Bark year ( ] )", "Inner ring ( { )", "Outer ring ( } )", "Dormant season scar ( D )", "Early earlywood scar ( E )", "Middle earlywood scar ( M )", "Late earlywood scar ( L )", "Undtermined season scar ( U )", "Early earlywood injury ( e )", "Middle earlywood injury ( m )", "Late earlywood injury ( l )", "Latewood injury ( a )", "undetermined season injury ( u )", "Recorder Year ( | )" }));

      jLabel28.setText("New Value");

      btnFillFifty.setText("Fill Selected Year(s)");
      btnFillFifty.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            btnFillFiftyActionPerformed(evt);
         }
      });

      txtSampleId.setText("Enter Sample Name...");

      btnchangeSampleID.setText("Change Sample ID");
      btnchangeSampleID.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            btnchangeSampleIDActionPerformed(evt);
         }
      });

      sampleListDropDown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "sample 1", "sample 2", "sample 3", " " }));

      fireHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][]
         {

         },
         new String []
         {
            "Year", "Value"
         }
      ));
      fireHistoryTable.setMaximumSize(new java.awt.Dimension(150, 0));
      jScrollPane2.setViewportView(fireHistoryTable);

      errorlbl1.setForeground(new java.awt.Color(255, 0, 0));
      errorlbl1.setText("Error: No Sample Selected");

      errorlbl2.setForeground(new java.awt.Color(255, 0, 51));
      errorlbl2.setText("Error: Name already in Set");

      errorlbl3.setForeground(new java.awt.Color(255, 0, 51));
      errorlbl3.setText("Error: ID length too long");

      maxSamplesize.setText("Max Sample ID Length: ");

      saveDataBtn.setText("Save Data");
      saveDataBtn.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            saveDataBtnActionPerformed(evt);
         }
      });

      modifyBtn.setText("Modify");
      modifyBtn.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            modifyBtnActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout fireHistoryPanelLayout = new javax.swing.GroupLayout(fireHistoryPanel);
      fireHistoryPanel.setLayout(fireHistoryPanelLayout);
      fireHistoryPanelLayout.setHorizontalGroup(
         fireHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(fireHistoryPanelLayout.createSequentialGroup()
            .addGroup(fireHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(fireHistoryPanelLayout.createSequentialGroup()
                  .addContainerGap()
                  .addGroup(fireHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(fireHistoryPanelLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSampleId, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(fireHistoryPanelLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(maxSamplesize)))
                  .addGap(18, 18, 18)
                  .addGroup(fireHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(errorlbl3)
                     .addComponent(btnchangeSampleID))
                  .addGap(54, 54, 54)
                  .addGroup(fireHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(sampleListDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGroup(fireHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(errorlbl2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(errorlbl1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(modifyBtn))
               .addGroup(fireHistoryPanelLayout.createSequentialGroup()
                  .addGap(26, 26, 26)
                  .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(46, 46, 46)
                  .addGroup(fireHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(fireHistoryPanelLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fireHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(btnFillFifty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(cmbNewValue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(saveDataBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                     .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap(121, Short.MAX_VALUE))
      );
      fireHistoryPanelLayout.setVerticalGroup(
         fireHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(fireHistoryPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(fireHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(fireHistoryPanelLayout.createSequentialGroup()
                  .addGap(20, 20, 20)
                  .addComponent(errorlbl2)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(fireHistoryPanelLayout.createSequentialGroup()
                  .addGroup(fireHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel27)
                     .addComponent(txtSampleId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(btnchangeSampleID)
                     .addComponent(sampleListDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(modifyBtn))
                  .addGroup(fireHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(fireHistoryPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(errorlbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fireHistoryPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(fireHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(errorlbl3)
                           .addComponent(maxSamplesize))
                        .addGap(18, 18, 18)))))
            .addGroup(fireHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(fireHistoryPanelLayout.createSequentialGroup()
                  .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(40, 40, 40)
                  .addGroup(fireHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel28)
                     .addComponent(cmbNewValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btnFillFifty)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(saveDataBtn))
               .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(95, 95, 95))
      );

      errorlbl2.getAccessibleContext().setAccessibleName("errorlbl2");

      jTabbedPane1.addTab("Fire History ", fireHistoryPanel);

      jMenu1.setText("File");

      mnuImportData.setText("Import Data");
      mnuImportData.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            mnuImportDataActionPerformed(evt);
         }
      });
      jMenu1.add(mnuImportData);

      mnuSaveFile.setText("Save File");
      mnuSaveFile.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            mnuSaveFileActionPerformed(evt);
         }
      });
      jMenu1.add(mnuSaveFile);

      jMenuBar1.add(jMenu1);

      jMenu2.setText("Help");

      jMenuItem1.setText("FHX2 Website");
      jMenuItem1.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jMenuItem1ActionPerformed(evt);
         }
      });
      jMenu2.add(jMenuItem1);

      jMenuBar1.add(jMenu2);

      setJMenuBar(jMenuBar1);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   /*
      updates site info when save btn is clicked
   */
   private void btnSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSaveActionPerformed
   {//GEN-HEADEREND:event_btnSaveActionPerformed
        updateSiteInfo();
   }//GEN-LAST:event_btnSaveActionPerformed

   /*
      updates the siteInfo[] with the text in each text boxes, then prints 
      to the file.
   */
   private void updateSiteInfo()
   {
      siteInfo = new String[30];
      int count = 0;
      siteInfo[count++] = txtSiteName.getText();
      siteInfo[count++] = txtSiteCode.getText();
      siteInfo[count++] = txtCollectionDate.getText(); 
      siteInfo[count++] = txtCollectors.getText();
      siteInfo[count++] = txtCrossDaters.getText();
      count++;
      siteInfo[count++] = txtSpeciesName.getText();
      siteInfo[count++] = txtCommonName.getText();
      siteInfo[count++] = txtHabitatType.getText();
      siteInfo[count++] = txtCountry.getText();
      siteInfo[count++] = txtState.getText();
      siteInfo[count++] = txtCounty.getText();
      siteInfo[count++] = txtParkMonument.getText();
      siteInfo[count++] = txtNationalForest.getText();
      siteInfo[count++] = txtRangerDistrict.getText();
      siteInfo[count++] = txtTownship.getText();
      siteInfo[count++] = txtRange.getText();
      siteInfo[count++] = txtSection.getText();
      siteInfo[count++] = txtQuarterSection.getText();
      siteInfo[count++] = txtUTMEasting.getText();
      siteInfo[count++] = txtUTMNorthing.getText();
      siteInfo[count++] = txtLatitude.getText();
      siteInfo[count++] = txtLongitude.getText();
      siteInfo[count++] = txtTopographicMap.getText();
      siteInfo[count++] = txtLowestElevation.getText();
      siteInfo[count++] = txtHighestElev.getText();
      siteInfo[count++] = txtSlope.getText();
      siteInfo[count++] = txtAspect.getText();
      siteInfo[count++] = txtAreaSampled.getText();
      siteInfo[count] = txtSubstrateType.getText();
      d.setSiteInformation(siteInfo);
      d.setOutputFileName(fileName);
      d.printFile();
   }
   
   /*
      deletes all text fields
   */
   private void btnDeleteAllActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDeleteAllActionPerformed
   {//GEN-HEADEREND:event_btnDeleteAllActionPerformed
      deleteAllFields();
   }//GEN-LAST:event_btnDeleteAllActionPerformed

   /*
      sets the start/end dates, sample num/idlength, and filename. Adds rows 
      to the fire history table, then sets the sample names
   */
   private void saveDataSet()
   {
        startDate = Integer.parseInt(txtFirstYear.getText());
        endDate = Integer.parseInt(txtLastYear.getText());
        sampleNum = Integer.parseInt(txtNumberOfSamples.getText());
        IDlen = Integer.parseInt(txtSampleIDLength.getText());
        fileName = txtFileName.getText();
        // ADDING ROWS TO FIRE HISTORY TABLE
        String header[] = new String[] { "Year", "Values" };
        DefaultTableModel dtm = new DefaultTableModel(0, 0);
        dtm.setColumnIdentifiers(header);
        fireHistoryTable.setModel(dtm);
         for( int i = 0; i <= (endDate - startDate); i++ )
         {
           dtm.addRow(
                 new String[]{ new Integer(startDate + i).toString(), "" } );
         }

        // SETUP SAMPLE LIST
      if (fileLoaded)
      {
         setSampleNamesFromFile();
         d.sHandle.changeSampleNames(d.getSampleIDInfo());
      }
      else
      {
         deleteAllFields();
         d.sHandle = new SampleHandler(sampleNum, startDate, endDate, IDlen, true, null);
         updateSiteInfo();
         d.eraseComments();
         Vector dropDownItems = new Vector();
         for( int i = 0; i < sampleNum; i++)
            dropDownItems.add( new Integer(i + 1).toString() );
         final DefaultComboBoxModel model = new DefaultComboBoxModel(dropDownItems);
         sampleListDropDown.setModel(model);
         d.setOutputFileName(fileName);
         d.setNumberOfSamples(sampleNum);
         d.setStartYear(startDate);
         d.setEndYear(endDate);
         d.setSampleIDLength(IDlen);
         d.printFile();
      }
   }
   
   /*
      clears all text fields
   */
   private void deleteAllFields()
   {
      txtSiteName.setText("");
      txtSiteCode.setText("");
      txtCollectionDate.setText("");
      txtCollectors.setText("");
      txtCrossDaters.setText("");
      txtSpeciesName.setText("");
      txtCommonName.setText("");
      txtHabitatType.setText("");
      txtCountry.setText("");
      txtState.setText("");
      txtCounty.setText("");
      txtParkMonument.setText("");
      txtNationalForest.setText("");
      txtRangerDistrict.setText("");
      txtTownship.setText("");
      txtRange.setText("");
      txtSection.setText("");
      txtQuarterSection.setText("");
      txtUTMEasting.setText("");
      txtUTMNorthing.setText("");
      txtLatitude.setText("");
      txtLongitude.setText("");
      txtTopographicMap.setText("");
      txtLowestElevation.setText("");
      txtHighestElev.setText("");
      txtSlope.setText("");
      txtAspect.setText("");
      txtAreaSampled.setText("");
      txtSubstrateType.setText("");
      txtStartYear.setText("");
      txtEndYear.setText("");
      txtNumSamples.setText("");
   }
   
   /*
      adds dropdown items from the array of sample IDs
   */
   private void setSampleNamesFromFile()
   {
      char[] sampleID = new char[d.getSampleIDLength()];
      Vector dropDownItems = new Vector();
      for (int i = 0; i < d.getNumberOfSamples(); i++)
      {
         for (int j = 0; j < d.getSampleIDLength(); j++)
         {
            sampleID[j] = d.getSampleIDInfoAt(j, i);
         }
         dropDownItems.add( new String(sampleID) );
      }
      final DefaultComboBoxModel model = new DefaultComboBoxModel(dropDownItems);
      sampleListDropDown.setModel(model);
   }
   
   /*
      Saves the data set, and prints to file, unless there are empty textfields
   */
   private void saveDataSetBtn1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saveDataSetBtn1ActionPerformed
   {//GEN-HEADEREND:event_saveDataSetBtn1ActionPerformed
      if (txtFirstYear.getText().isEmpty() || 
            txtLastYear.getText().isEmpty() || 
            txtNumberOfSamples.getText().isEmpty() || 
            txtSampleIDLength.getText().isEmpty() ||
            txtFileName.getText().isEmpty())
      {  
         JOptionPane.showMessageDialog(null, "The Data Information "
            + "has not been properly inserted. "
            + "\nPlease check the entered values under the 'Data Settings' Tab",
            "InfoBox Incorrect Data", JOptionPane.INFORMATION_MESSAGE);
      }
      else
      {
         saveDataSet();
         this.fileName = txtFileName.getText();
         d.setOutputFileName(fileName);
         d.printFile();
         maxSamplesize.setText("Max Sample ID Length: " + IDlen);
      }
   }//GEN-LAST:event_saveDataSetBtn1ActionPerformed

   /*
      Fills the selected indices of the fire history data table with the
      selected char value
   */
   private void btnFillFiftyActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnFillFiftyActionPerformed
   {//GEN-HEADEREND:event_btnFillFiftyActionPerformed
      try{
         String value = new String(cmbNewValue.getSelectedItem().toString());
         value = value.substring(value.lastIndexOf('(') + 1);
         value = value.substring(1, 2);
         int yearsToEdit[] = fireHistoryTable.getSelectedRows();
         for( int i = yearsToEdit[0]; i <= yearsToEdit[yearsToEdit.length - 1]; i++)
            fireHistoryTable.setValueAt( value, i, 1 );
      }
      catch(Exception e)
      {
         System.out.println("Create a data set or use an existing one!");
      }
   }//GEN-LAST:event_btnFillFiftyActionPerformed

   /*
      Imports an already created file into the system. Fills corresponding
      textfields with known information
   */
    private void mnuImportDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuImportDataActionPerformed
        //Create a file chooser
        final JFileChooser fc = new JFileChooser();

        int returnVal;
        returnVal = fc.showOpenDialog(this);
        
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            //This is where a real application would open the file.
            d.readFromFile(file.getAbsolutePath());
            String test[] = d.getSiteInfo();
            
            this.txtAreaSampled.setText(test[d.dataLocs.areaSampled]);
            this.txtAspect.setText(test[d.dataLocs.aspect]);
            this.txtCollectionDate.setText(test[d.dataLocs.collectionDate]);
            this.txtCollectors.setText(test[d.dataLocs.collectors]);
            this.txtCommonName.setText(test[d.dataLocs.commonName]);
            this.txtCountry.setText(test[d.dataLocs.country]);
            this.txtCounty.setText(test[d.dataLocs.county]);
            this.txtCrossDaters.setText(test[d.dataLocs.crossdaters]); ;
            this.txtHabitatType.setText(test[d.dataLocs.habitatType]);          
            this.txtHighestElev.setText(test[d.dataLocs.highestElev]);         
            this.txtLatitude.setText(test[d.dataLocs.latitude]);         
            this.txtLongitude.setText(test[d.dataLocs.longitude]);         
            this.txtLowestElevation.setText(test[d.dataLocs.lowestElev]);         
            this.txtSiteName.setText(test[d.dataLocs.nameOfSite]);         
            this.txtNationalForest.setText(test[d.dataLocs.nationalForest]);         
            this.txtNumSamples.setText(Integer.toString(d.getNumberOfSamples()));          
            this.txtParkMonument.setText(test[d.dataLocs.parkMonument]);         
            this.txtQuarterSection.setText(test[d.dataLocs.quarterSection]);        
            this.txtRange.setText(test[d.dataLocs.range]);    
            this.txtRangerDistrict.setText(test[d.dataLocs.rangerDistrict]);          
            this.txtSection.setText(test[d.dataLocs.section]);      
            this.txtSiteCode.setText(test[d.dataLocs.siteCode]);       
            this.txtSlope.setText(test[d.dataLocs.slope]);   
            this.txtSpeciesName.setText(test[d.dataLocs.speciesName]);     
            this.txtState.setText(test[d.dataLocs.state]); 
            this.txtSubstrateType.setText(test[d.dataLocs.substrateType]);
            this.txtTopographicMap.setText(test[d.dataLocs.topographicMap]);
            this.txtTownship.setText(test[d.dataLocs.township]);
            this.txtUTMEasting.setText(test[d.dataLocs.utmEasting]);
            this.txtUTMNorthing.setText(test[d.dataLocs.utmNorthing]);
            this.txtStartYear.setText(Integer.toString(d.getStartYear()));
            this.txtEndYear.setText(Integer.toString(d.getEndYear()));
            this.txtFirstYear.setText(Integer.toString(d.getStartYear()));
            this.txtLastYear.setText(Integer.toString(d.getEndYear()));
            this.txtNumberOfSamples.setText(Integer.toString(d.getNumberOfSamples()));
            this.txtSampleIDLength.setText(Integer.toString(d.getSampleIDLength()));
            this.txtFileName.setText(d.getInputFileName());
            
            fileLoaded = true;
            d.sHandle = new SampleHandler(d.getNumberOfSamples(), d.getStartYear(), 
                                          d.getEndYear(), d.getSampleIDLength(), 
                                          false, d.getInfo());
            for(int i = 0; i < d.getNumberOfSamples(); i++)
                sampleListDropDown.addItem(d.sHandle.getSample(i));
            saveDataSet();
        } 
        
    }//GEN-LAST:event_mnuImportDataActionPerformed

    /*
      changes the sample ID of a selected sample, gives errors for new
      id length and more.
    */
   private void btnchangeSampleIDActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnchangeSampleIDActionPerformed
   {//GEN-HEADEREND:event_btnchangeSampleIDActionPerformed
      try{  
         if( txtSampleId.getText().length() <= IDlen )
         {   
            String Id = txtSampleId.getText();
            String oldString = (String) sampleListDropDown.getSelectedItem();
            int errorCode = d.sHandle.changeId(Id, (String)sampleListDropDown.getSelectedItem());
            if(errorCode == 0)
                errorlbl1.setVisible(true);
            else if(errorCode == -1)
                errorlbl2.setVisible(true);
            else
            {
                errorlbl2.setVisible(false);
                errorlbl1.setVisible(false);
                errorlbl3.setVisible(false);
                sampleListDropDown.removeAllItems();
                d.sHandle.changeId(Id, oldString);
                String [] samples = d.sHandle.refreshIdnames();
                for(int i = 0; i < samples.length; i++)
                    sampleListDropDown.addItem(samples[i]);
            }
         }
         else
            errorlbl3.setVisible(true);
      }
      catch(Exception e)
      {
         System.out.println("Error: " + e);
      }
   }//GEN-LAST:event_btnchangeSampleIDActionPerformed

   /*
      Saves the data in the fire history data table for a chosen sample
      once it has been modified.
   */
   private void modifyBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_modifyBtnActionPerformed
   {//GEN-HEADEREND:event_modifyBtnActionPerformed
      try{
         char tempData[];
         tempData = new char[endDate - startDate + 1];
         String id = (String)sampleListDropDown.getSelectedItem();
         tempData = d.sHandle.getSampleInfo(id);
         String header[] = new String[] { "Year", "Values" };
         DefaultTableModel dtm = new DefaultTableModel(0, 0);
         dtm.setColumnIdentifiers(header);
         fireHistoryTable.setModel(dtm);
         for( int i = 0; i < (endDate - startDate + 1); i++ )
         {
            dtm.addRow(new String[]{ new Integer(startDate + i).toString(), 
                                       "" } );
            fireHistoryTable.setValueAt(tempData[i], i, 1);
         }
      }
      catch(Exception e)
      {
         System.out.println("Create a data set or use an existing one!");
      }
      
      
   }//GEN-LAST:event_modifyBtnActionPerformed

   /*
      reset the site info data fields to what the system last knew them as
   */
   private void resetDataFieldsBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_resetDataFieldsBtnActionPerformed
   {//GEN-HEADEREND:event_resetDataFieldsBtnActionPerformed
      if (!fileLoaded)
         return;   
      String test[] = d.getSiteInfo();      
      this.txtAreaSampled.setText(test[d.dataLocs.areaSampled]);
      this.txtAspect.setText(test[d.dataLocs.aspect]);
      this.txtCollectionDate.setText(test[d.dataLocs.collectionDate]);
      this.txtCollectors.setText(test[d.dataLocs.collectors]);
      this.txtCommonName.setText(test[d.dataLocs.commonName]);
      this.txtCountry.setText(test[d.dataLocs.country]);
      this.txtCounty.setText(test[d.dataLocs.county]);
      this.txtCrossDaters.setText(test[d.dataLocs.crossdaters]);
      this.txtHabitatType.setText(test[d.dataLocs.habitatType]);
      this.txtHighestElev.setText(test[d.dataLocs.highestElev]);
      this.txtLatitude.setText(test[d.dataLocs.latitude]);
      this.txtLongitude.setText(test[d.dataLocs.longitude]);
      this.txtLowestElevation.setText(test[d.dataLocs.lowestElev]);
      this.txtSiteName.setText(test[d.dataLocs.nameOfSite]);
      this.txtNationalForest.setText(test[d.dataLocs.nationalForest]);
      this.txtNumSamples.setText(Integer.toString(d.getNumberOfSamples()));
      this.txtParkMonument.setText(test[d.dataLocs.parkMonument]);
      this.txtQuarterSection.setText(test[d.dataLocs.quarterSection]);
      this.txtRange.setText(test[d.dataLocs.range]);
      this.txtRangerDistrict.setText(test[d.dataLocs.rangerDistrict]);
      this.txtSection.setText(test[d.dataLocs.section]);
      this.txtSiteCode.setText(test[d.dataLocs.siteCode]);
      this.txtSlope.setText(test[d.dataLocs.slope]);
      this.txtSpeciesName.setText(test[d.dataLocs.speciesName]);
      this.txtState.setText(test[d.dataLocs.state]);
      this.txtSubstrateType.setText(test[d.dataLocs.substrateType]);
      this.txtTopographicMap.setText(test[d.dataLocs.topographicMap]);
      this.txtTownship.setText(test[d.dataLocs.township]);
      this.txtUTMEasting.setText(test[d.dataLocs.utmEasting]);
      this.txtUTMNorthing.setText(test[d.dataLocs.utmNorthing]);
      this.txtStartYear.setText(Integer.toString(d.getStartYear()));
      this.txtEndYear.setText(Integer.toString(d.getEndYear()));
      this.txtFirstYear.setText(Integer.toString(d.getStartYear()));
      this.txtLastYear.setText(Integer.toString(d.getEndYear()));
      this.txtNumberOfSamples.setText(Integer.toString(d.getNumberOfSamples()));
      this.txtSampleIDLength.setText(Integer.toString(d.getSampleIDLength()));
      this.txtFileName.setText(d.getInputFileName());
   }//GEN-LAST:event_resetDataFieldsBtnActionPerformed

   /*
      saves the fire history data table and prints it to file
   */
    private void saveDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDataBtnActionPerformed
        try{
           char tempData[];
           tempData = new char[fireHistoryTable.getRowCount()];
           //tempData = new char[fireHistoryTable.getRowCount() + 1];
           int index = sampleListDropDown.getSelectedIndex();
           for( int i = 0; i < fireHistoryTable.getRowCount(); i++)
           {
              String s = fireHistoryTable.getValueAt(i, 1).toString();
              tempData[i] = s.charAt(0);
           }
           //String last = fireHistoryTable.getValueAt(fireHistoryTable.getRowCount() - 1, 1).toString();
           //tempData[fireHistoryTable.getRowCount()] = last.charAt(0);
           d.sHandle.changeSampleData(tempData, index);
           d.setOutputFileName(txtFileName.getText());
           d.printFile();
        }
        catch(Exception e)
        {
           System.out.println("Create a data set or use an existing one!");
        }
    }//GEN-LAST:event_saveDataBtnActionPerformed

    /*
      not used
    */
   private void txtFileNameKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtFileNameKeyTyped
   {//GEN-HEADEREND:event_txtFileNameKeyTyped
      //fileLoaded = false;
   }//GEN-LAST:event_txtFileNameKeyTyped

   /*
      Saves the data set unless there is no data in correspoding text fields,
      and then prints to file
   */
   private void mnuSaveFileActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuSaveFileActionPerformed
   {//GEN-HEADEREND:event_mnuSaveFileActionPerformed
      if(txtFirstYear.getText().isEmpty() || 
            txtLastYear.getText().isEmpty() || 
            txtNumberOfSamples.getText().isEmpty() || 
            txtSampleIDLength.getText().isEmpty() ||
            txtFileName.getText().isEmpty())
      {
         JOptionPane.showMessageDialog(null, "The Data Information "
            + "has not been properly inserted. "
            + "\nPlease check the entered values under the 'Data Settings' Tab",
            "InfoBox Incorrect Data", JOptionPane.INFORMATION_MESSAGE);
      }
      else
      {
         saveDataSet();
         fileName = txtFileName.getText();
         d.setOutputFileName(fileName);
         d.printFile();
      }
   }//GEN-LAST:event_mnuSaveFileActionPerformed

   /*
      opens up the fhx website
   */
   private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem1ActionPerformed
   {//GEN-HEADEREND:event_jMenuItem1ActionPerformed
      try
      {
         java.awt.Desktop.getDesktop().browse(java.net.URI.create(Constants.FHX2_SITE));
      }
      catch (Exception e)
      {
         System.out.println("Error: " + e);
      }
   }//GEN-LAST:event_jMenuItem1ActionPerformed

   /*
      Saves the data set unless there is no data in correspoding text fields,
      and then prints to file
   */
   private void saveDataSetBtn2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saveDataSetBtn2ActionPerformed
   {//GEN-HEADEREND:event_saveDataSetBtn2ActionPerformed
      fileLoaded = false;
      if(txtFirstYear.getText().isEmpty() || 
            txtLastYear.getText().isEmpty() || 
            txtNumberOfSamples.getText().isEmpty() || 
            txtSampleIDLength.getText().isEmpty() ||
            txtFileName.getText().isEmpty())
      {
         JOptionPane.showMessageDialog(null, "The Data Information "
            + "has not been properly inserted. "
            + "\nPlease check the entered values under the 'Data Settings' Tab",
            "InfoBox Incorrect Data", JOptionPane.INFORMATION_MESSAGE);
      }
      else
      {
         saveDataSet();
         fileName = txtFileName.getText();
         d.setOutputFileName(fileName);
         d.printFile();
      }
   }//GEN-LAST:event_saveDataSetBtn2ActionPerformed

   /*
      resets all of the textfields for data settings
   */
   private void resetAllFieldsDataActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_resetAllFieldsDataActionPerformed
   {//GEN-HEADEREND:event_resetAllFieldsDataActionPerformed
      txtFirstYear.setText("");
      txtLastYear.setText("");
      txtNumberOfSamples.setText("");
      txtSampleIDLength.setText("");
      txtFileName.setText("");
   }//GEN-LAST:event_resetAllFieldsDataActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[])
   {
      /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try
      {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
         {
            if ("Nimbus".equals(info.getName()))
            {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex)
      {
         java.util.logging.Logger.getLogger(HomeGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex)
      {
         java.util.logging.Logger.getLogger(HomeGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex)
      {
         java.util.logging.Logger.getLogger(HomeGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex)
      {
         java.util.logging.Logger.getLogger(HomeGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
        //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new HomeGui().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnDeleteAll;
   private javax.swing.JButton btnFillFifty;
   private javax.swing.JButton btnSave;
   private javax.swing.JButton btnchangeSampleID;
   private javax.swing.JComboBox cmbNewValue;
   private javax.swing.JPanel dataSettingsPanel;
   private javax.swing.JLabel errorlbl1;
   private javax.swing.JLabel errorlbl2;
   private javax.swing.JLabel errorlbl3;
   private javax.swing.JPanel fireHistoryPanel;
   private javax.swing.JTable fireHistoryTable;
   private javax.swing.JPanel homePanel;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel10;
   private javax.swing.JLabel jLabel11;
   private javax.swing.JLabel jLabel12;
   private javax.swing.JLabel jLabel13;
   private javax.swing.JLabel jLabel14;
   private javax.swing.JLabel jLabel15;
   private javax.swing.JLabel jLabel16;
   private javax.swing.JLabel jLabel17;
   private javax.swing.JLabel jLabel18;
   private javax.swing.JLabel jLabel19;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel20;
   private javax.swing.JLabel jLabel21;
   private javax.swing.JLabel jLabel22;
   private javax.swing.JLabel jLabel23;
   private javax.swing.JLabel jLabel24;
   private javax.swing.JLabel jLabel25;
   private javax.swing.JLabel jLabel26;
   private javax.swing.JLabel jLabel27;
   private javax.swing.JLabel jLabel28;
   private javax.swing.JLabel jLabel29;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel30;
   private javax.swing.JLabel jLabel31;
   private javax.swing.JLabel jLabel32;
   private javax.swing.JLabel jLabel33;
   private javax.swing.JLabel jLabel34;
   private javax.swing.JLabel jLabel35;
   private javax.swing.JLabel jLabel36;
   private javax.swing.JLabel jLabel37;
   private javax.swing.JLabel jLabel38;
   private javax.swing.JLabel jLabel39;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel40;
   private javax.swing.JLabel jLabel41;
   private javax.swing.JLabel jLabel42;
   private javax.swing.JLabel jLabel43;
   private javax.swing.JLabel jLabel44;
   private javax.swing.JLabel jLabel45;
   private javax.swing.JLabel jLabel46;
   private javax.swing.JLabel jLabel47;
   private javax.swing.JLabel jLabel48;
   private javax.swing.JLabel jLabel49;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel50;
   private javax.swing.JLabel jLabel51;
   private javax.swing.JLabel jLabel52;
   private javax.swing.JLabel jLabel53;
   private javax.swing.JLabel jLabel54;
   private javax.swing.JLabel jLabel55;
   private javax.swing.JLabel jLabel56;
   private javax.swing.JLabel jLabel57;
   private javax.swing.JLabel jLabel58;
   private javax.swing.JLabel jLabel59;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel60;
   private javax.swing.JLabel jLabel61;
   private javax.swing.JLabel jLabel62;
   private javax.swing.JLabel jLabel63;
   private javax.swing.JLabel jLabel64;
   private javax.swing.JLabel jLabel65;
   private javax.swing.JLabel jLabel66;
   private javax.swing.JLabel jLabel67;
   private javax.swing.JLabel jLabel68;
   private javax.swing.JLabel jLabel69;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel70;
   private javax.swing.JLabel jLabel71;
   private javax.swing.JLabel jLabel72;
   private javax.swing.JLabel jLabel73;
   private javax.swing.JLabel jLabel74;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JMenu jMenu1;
   private javax.swing.JMenu jMenu2;
   private javax.swing.JMenuBar jMenuBar1;
   private javax.swing.JMenuItem jMenuItem1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JScrollPane jScrollPane3;
   private javax.swing.JScrollPane jScrollPane4;
   private javax.swing.JSeparator jSeparator1;
   private javax.swing.JSeparator jSeparator2;
   private javax.swing.JSeparator jSeparator3;
   private javax.swing.JSeparator jSeparator4;
   private javax.swing.JTabbedPane jTabbedPane1;
   private javax.swing.JTextArea jTextArea1;
   private javax.swing.JTextArea jTextArea2;
   private javax.swing.JTextArea jTextArea3;
   private javax.swing.JLabel maxSamplesize;
   private javax.swing.JMenuItem mnuImportData;
   private javax.swing.JMenuItem mnuSaveFile;
   private javax.swing.JButton modifyBtn;
   private javax.swing.JButton resetAllFieldsData;
   private javax.swing.JButton resetDataFieldsBtn;
   private javax.swing.JComboBox sampleListDropDown;
   private javax.swing.JButton saveDataBtn;
   private javax.swing.JButton saveDataSetBtn1;
   private javax.swing.JButton saveDataSetBtn2;
   private javax.swing.JPanel siteInfoPanel;
   private javax.swing.JTextField txtAreaSampled;
   private javax.swing.JTextField txtAspect;
   private javax.swing.JTextField txtCollectionDate;
   private javax.swing.JTextField txtCollectors;
   private javax.swing.JTextField txtCommonName;
   private javax.swing.JTextField txtCountry;
   private javax.swing.JTextField txtCounty;
   private javax.swing.JTextField txtCrossDaters;
   private javax.swing.JTextField txtEndYear;
   private javax.swing.JTextField txtFileName;
   private javax.swing.JTextField txtFirstYear;
   private javax.swing.JTextField txtHabitatType;
   private javax.swing.JTextField txtHighestElev;
   private javax.swing.JTextField txtLastYear;
   private javax.swing.JTextField txtLatitude;
   private javax.swing.JTextField txtLongitude;
   private javax.swing.JTextField txtLowestElevation;
   private javax.swing.JTextField txtNationalForest;
   private javax.swing.JTextField txtNumSamples;
   private javax.swing.JTextField txtNumberOfSamples;
   private javax.swing.JTextField txtParkMonument;
   private javax.swing.JTextField txtQuarterSection;
   private javax.swing.JTextField txtRange;
   private javax.swing.JTextField txtRangerDistrict;
   private javax.swing.JTextField txtSampleIDLength;
   private javax.swing.JTextField txtSampleId;
   private javax.swing.JTextField txtSection;
   private javax.swing.JTextField txtSiteCode;
   private javax.swing.JTextField txtSiteName;
   private javax.swing.JTextField txtSlope;
   private javax.swing.JTextField txtSpeciesName;
   private javax.swing.JTextField txtStartYear;
   private javax.swing.JTextField txtState;
   private javax.swing.JTextField txtSubstrateType;
   private javax.swing.JTextField txtTopographicMap;
   private javax.swing.JTextField txtTownship;
   private javax.swing.JTextField txtUTMEasting;
   private javax.swing.JTextField txtUTMNorthing;
   // End of variables declaration//GEN-END:variables
}
