/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se3860_secondgui;

/**
 *
 * @author Nathan
 */
public class HomeGui extends javax.swing.JFrame
{

   /**
    * Creates new form HomeGui
    */
   public HomeGui()
   {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      jTabbedPane1 = new javax.swing.JTabbedPane();
      homePanel = new javax.swing.JPanel();
      jLabel72 = new javax.swing.JLabel();
      siteInfoPanel = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      txtSiteName = new javax.swing.JTextField();
      jLabel2 = new javax.swing.JLabel();
      txtParkMonument = new javax.swing.JTextField();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      txtSiteCode = new javax.swing.JTextField();
      jLabel5 = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      txtNationalForest = new javax.swing.JTextField();
      jLabel7 = new javax.swing.JLabel();
      jLabel8 = new javax.swing.JLabel();
      txtRangerDistrict = new javax.swing.JTextField();
      jLabel9 = new javax.swing.JLabel();
      jLabel10 = new javax.swing.JLabel();
      txtTopographicMap = new javax.swing.JTextField();
      jLabel11 = new javax.swing.JLabel();
      jLabel12 = new javax.swing.JLabel();
      txtCollectors = new javax.swing.JTextField();
      jLabel13 = new javax.swing.JLabel();
      jLabel14 = new javax.swing.JLabel();
      txtState = new javax.swing.JTextField();
      jLabel15 = new javax.swing.JLabel();
      jLabel16 = new javax.swing.JLabel();
      txtSpeciesName = new javax.swing.JTextField();
      jLabel17 = new javax.swing.JLabel();
      jLabel18 = new javax.swing.JLabel();
      txtTownship = new javax.swing.JTextField();
      jLabel19 = new javax.swing.JLabel();
      jLabel20 = new javax.swing.JLabel();
      txtCountry = new javax.swing.JTextField();
      jLabel21 = new javax.swing.JLabel();
      jLabel22 = new javax.swing.JLabel();
      txtNumSamples = new javax.swing.JTextField();
      jLabel23 = new javax.swing.JLabel();
      jLabel24 = new javax.swing.JLabel();
      txtCrossDaters = new javax.swing.JTextField();
      jLabel25 = new javax.swing.JLabel();
      jLabel26 = new javax.swing.JLabel();
      txtQuarterSection = new javax.swing.JTextField();
      jLabel29 = new javax.swing.JLabel();
      jLabel30 = new javax.swing.JLabel();
      txtAreaSampled = new javax.swing.JTextField();
      jLabel31 = new javax.swing.JLabel();
      jLabel32 = new javax.swing.JLabel();
      txtHabitatType = new javax.swing.JTextField();
      jLabel33 = new javax.swing.JLabel();
      jLabel34 = new javax.swing.JLabel();
      txtSection = new javax.swing.JTextField();
      jLabel35 = new javax.swing.JLabel();
      jLabel36 = new javax.swing.JLabel();
      txtCounty = new javax.swing.JTextField();
      jLabel37 = new javax.swing.JLabel();
      jLabel38 = new javax.swing.JLabel();
      txtCommonName = new javax.swing.JTextField();
      jLabel39 = new javax.swing.JLabel();
      jLabel40 = new javax.swing.JLabel();
      txtRange = new javax.swing.JTextField();
      jLabel41 = new javax.swing.JLabel();
      jLabel42 = new javax.swing.JLabel();
      txtUTMNorthing = new javax.swing.JTextField();
      jLabel43 = new javax.swing.JLabel();
      jLabel44 = new javax.swing.JLabel();
      txtUTMEasting = new javax.swing.JTextField();
      jLabel45 = new javax.swing.JLabel();
      jLabel46 = new javax.swing.JLabel();
      txtAspect = new javax.swing.JTextField();
      jLabel47 = new javax.swing.JLabel();
      jLabel48 = new javax.swing.JLabel();
      txtSlope = new javax.swing.JTextField();
      jLabel49 = new javax.swing.JLabel();
      jLabel50 = new javax.swing.JLabel();
      txtHighestElev = new javax.swing.JTextField();
      jLabel51 = new javax.swing.JLabel();
      jLabel52 = new javax.swing.JLabel();
      txtLowestElevation = new javax.swing.JTextField();
      jLabel53 = new javax.swing.JLabel();
      jLabel54 = new javax.swing.JLabel();
      txtSubstrateType = new javax.swing.JTextField();
      jLabel55 = new javax.swing.JLabel();
      jLabel56 = new javax.swing.JLabel();
      txtStartYear = new javax.swing.JTextField();
      jLabel57 = new javax.swing.JLabel();
      jLabel58 = new javax.swing.JLabel();
      txtEndYear = new javax.swing.JTextField();
      jLabel59 = new javax.swing.JLabel();
      jLabel60 = new javax.swing.JLabel();
      txtLatitude = new javax.swing.JTextField();
      jLabel61 = new javax.swing.JLabel();
      jLabel62 = new javax.swing.JLabel();
      txtLongtitude = new javax.swing.JTextField();
      jLabel63 = new javax.swing.JLabel();
      jLabel64 = new javax.swing.JLabel();
      btnSave = new javax.swing.JButton();
      btnDeleteAll = new javax.swing.JButton();
      jSeparator1 = new javax.swing.JSeparator();
      jSeparator2 = new javax.swing.JSeparator();
      jSeparator3 = new javax.swing.JSeparator();
      fireHistoryPanel = new javax.swing.JPanel();
      jLabel27 = new javax.swing.JLabel();
      cmbSampleID = new javax.swing.JComboBox();
      jScrollPane4 = new javax.swing.JScrollPane();
      dataEntryDataList = new javax.swing.JList();
      jLabel65 = new javax.swing.JLabel();
      jLabel66 = new javax.swing.JLabel();
      jScrollPane1 = new javax.swing.JScrollPane();
      jTextArea1 = new javax.swing.JTextArea();
      cmbNewValue = new javax.swing.JComboBox();
      jLabel28 = new javax.swing.JLabel();
      btnFillFifty = new javax.swing.JButton();
      dataSettingsPanel = new javax.swing.JPanel();
      jLabel67 = new javax.swing.JLabel();
      firstYearTextField = new javax.swing.JTextField();
      sampleIDLengthTextField = new javax.swing.JTextField();
      lastYearTextField1 = new javax.swing.JTextField();
      numberOfSamplesTextField = new javax.swing.JTextField();
      cancelBtn = new javax.swing.JButton();
      saveDataSetBtn1 = new javax.swing.JButton();
      jLabel68 = new javax.swing.JLabel();
      jLabel69 = new javax.swing.JLabel();
      jLabel70 = new javax.swing.JLabel();
      sampleIDLengthTextField1 = new javax.swing.JTextField();
      jLabel71 = new javax.swing.JLabel();
      jMenuBar1 = new javax.swing.JMenuBar();
      jMenu1 = new javax.swing.JMenu();
      mnuImportData = new javax.swing.JMenuItem();
      mnuSaveFile = new javax.swing.JMenuItem();
      jMenu2 = new javax.swing.JMenu();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("FHX2 GUI - SE3860");

      jLabel72.setText("* Fill Later with Information");

      javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
      homePanel.setLayout(homePanelLayout);
      homePanelLayout.setHorizontalGroup(
         homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(homePanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel72)
            .addContainerGap(733, Short.MAX_VALUE))
      );
      homePanelLayout.setVerticalGroup(
         homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(homePanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel72)
            .addContainerGap(583, Short.MAX_VALUE))
      );

      jTabbedPane1.addTab("Home", homePanel);

      jLabel1.setText("Name of Site");

      txtSiteName.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            txtSiteNameActionPerformed(evt);
         }
      });

      jLabel2.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel2.setText("* Max 70 Characters");

      jLabel3.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel3.setText("* Max 70 Characters");

      jLabel4.setText("Park/Monument");

      jLabel5.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel5.setText("* Max 70 Characters");

      jLabel6.setText("Site Code");

      jLabel7.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel7.setText("* Max 70 Characters");

      jLabel8.setText("National Forest");

      jLabel9.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel9.setText("* Max 70 Characters");

      jLabel10.setText("Ranger District");

      jLabel11.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel11.setText("* Max 70 Characters");

      jLabel12.setText("Topographic Map");

      jLabel13.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel13.setText("* Max 70 Characters");

      jLabel14.setText("Collectors");

      jLabel15.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel15.setText("* Max 70 Characters");

      jLabel16.setText("State");

      jLabel17.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel17.setText("* Max 70 Characters");

      jLabel18.setText("Species Name");

      jLabel19.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel19.setText("* Max 70 Characters");

      jLabel20.setText("Township");

      jLabel21.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel21.setText("* Max 70 Characters");

      jLabel22.setText("Country");

      jLabel23.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel23.setText("* Max 70 Characters");

      jLabel24.setText("Number of Samples");

      jLabel25.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel25.setText("* Max 70 Characters");

      jLabel26.setText("CrossDaters");

      jLabel29.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel29.setText("* Max 70 Characters");

      jLabel30.setText("Quarter Section");

      jLabel31.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel31.setText("* Max 70 Characters");

      jLabel32.setText("Area Sampled");

      jLabel33.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel33.setText("* Max 70 Characters");

      jLabel34.setText("Habitat Type");

      jLabel35.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel35.setText("* Max 70 Characters");

      jLabel36.setText("Section");

      jLabel37.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel37.setText("* Max 70 Characters");

      jLabel38.setText("County");

      jLabel39.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel39.setText("* Max 70 Characters");

      jLabel40.setText("Common Name");

      jLabel41.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel41.setText("* Max 70 Characters");

      jLabel42.setText("Range");

      jLabel43.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel43.setText("* Max 70 Characters");

      jLabel44.setText("UTM Northing");

      jLabel45.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel45.setText("* Max 70 Characters");

      jLabel46.setText("UTM Easting");

      jLabel47.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel47.setText("* Max 70 Characters");

      jLabel48.setText("Aspect");

      jLabel49.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel49.setText("* Max 70 Characters");

      jLabel50.setText("Slope");

      jLabel51.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel51.setText("* Max 70 Characters");

      jLabel52.setText("Highest Elevation");

      jLabel53.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel53.setText("* Max 70 Characters");

      jLabel54.setText("Lowest Elevation");

      jLabel55.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel55.setText("* Max 70 Characters");

      jLabel56.setText("Substrate Type");

      jLabel57.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel57.setText("* Max 70 Characters");

      jLabel58.setText("Start Year");

      jLabel59.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel59.setText("* Max 70 Characters");

      jLabel60.setText("End Year");

      jLabel61.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel61.setText("* Max 70 Characters");

      jLabel62.setText("Latitude");

      jLabel63.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
      jLabel63.setText("* Max 70 Characters");

      jLabel64.setText("Longtitude");

      btnSave.setText("Save");

      btnDeleteAll.setText("Delete All");

      jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
      jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

      jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
      jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

      jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
      jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

      javax.swing.GroupLayout siteInfoPanelLayout = new javax.swing.GroupLayout(siteInfoPanel);
      siteInfoPanel.setLayout(siteInfoPanelLayout);
      siteInfoPanelLayout.setHorizontalGroup(
         siteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(siteInfoPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(siteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel3)
               .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtParkMonument, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel2)
               .addComponent(txtSiteName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtSiteCode, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel7)
               .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtNationalForest, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel9)
               .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtRangerDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel11)
               .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtTopographicMap, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel13)
               .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtCollectors, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel57)
               .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel5))
            .addGap(50, 50, 50)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(50, 50, 50)
            .addGroup(siteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel25)
               .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtCrossDaters, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel23)
               .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtNumSamples, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel21)
               .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel19)
               .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtTownship, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel17)
               .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtSpeciesName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel15)
               .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel59)
               .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtEndYear, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel37)
               .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtCounty, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(50, 50, 50)
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(50, 50, 50)
            .addGroup(siteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel39)
               .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtCommonName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel35)
               .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtSection, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel33)
               .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtHabitatType, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel31)
               .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtAreaSampled, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel29)
               .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtQuarterSection, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel41)
               .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtRange, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel55)
               .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtSubstrateType, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel61)
               .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(50, 50, 50)
            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(50, 50, 50)
            .addGroup(siteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel53)
               .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtLowestElevation, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel51)
               .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtHighestElev, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel49)
               .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtSlope, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel47)
               .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtAspect, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel45)
               .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtUTMEasting, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel43)
               .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtUTMNorthing, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel63)
                  .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(txtLongtitude, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGroup(siteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                     .addComponent(btnDeleteAll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                     .addComponent(btnSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addContainerGap())
      );
      siteInfoPanelLayout.setVerticalGroup(
         siteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(siteInfoPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(siteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(siteInfoPanelLayout.createSequentialGroup()
                  .addGroup(siteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(siteInfoPanelLayout.createSequentialGroup()
                        .addGroup(siteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addGroup(siteInfoPanelLayout.createSequentialGroup()
                              .addComponent(jLabel1)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel2)
                              .addGap(5, 5, 5)
                              .addComponent(txtSiteName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel4)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel3)
                              .addGap(5, 5, 5)
                              .addComponent(txtParkMonument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel6)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel5)
                              .addGap(5, 5, 5)
                              .addComponent(txtSiteCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel8)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel7)
                              .addGap(5, 5, 5)
                              .addComponent(txtNationalForest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel10)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel9)
                              .addGap(5, 5, 5)
                              .addComponent(txtRangerDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel12)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel11)
                              .addGap(5, 5, 5)
                              .addComponent(txtTopographicMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel14)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel13)
                              .addGap(5, 5, 5)
                              .addComponent(txtCollectors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addGroup(siteInfoPanelLayout.createSequentialGroup()
                              .addComponent(jLabel42)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel41)
                              .addGap(5, 5, 5)
                              .addComponent(txtRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel40)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel39)
                              .addGap(5, 5, 5)
                              .addComponent(txtCommonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(7, 7, 7)
                              .addComponent(jLabel36)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel35)
                              .addGap(5, 5, 5)
                              .addComponent(txtSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel34)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel33)
                              .addGap(5, 5, 5)
                              .addComponent(txtHabitatType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel32)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel31)
                              .addGap(5, 5, 5)
                              .addComponent(txtAreaSampled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel30)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel29)
                              .addGap(5, 5, 5)
                              .addComponent(txtQuarterSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel56)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel55)
                              .addGap(5, 5, 5)
                              .addComponent(txtSubstrateType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addGroup(siteInfoPanelLayout.createSequentialGroup()
                              .addComponent(jLabel54)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel53)
                              .addGap(5, 5, 5)
                              .addComponent(txtLowestElevation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel52)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel51)
                              .addGap(5, 5, 5)
                              .addComponent(txtHighestElev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel50)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel49)
                              .addGap(5, 5, 5)
                              .addComponent(txtSlope, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel48)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel47)
                              .addGap(5, 5, 5)
                              .addComponent(txtAspect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel46)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel45)
                              .addGap(5, 5, 5)
                              .addComponent(txtUTMEasting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel44)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel43)
                              .addGap(5, 5, 5)
                              .addComponent(txtUTMNorthing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel64)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel63)
                              .addGap(5, 5, 5)
                              .addComponent(txtLongtitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(siteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(siteInfoPanelLayout.createSequentialGroup()
                              .addComponent(jLabel58)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel57)
                              .addGap(5, 5, 5)
                              .addComponent(txtStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addGroup(siteInfoPanelLayout.createSequentialGroup()
                              .addComponent(jLabel60)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel59)
                              .addGap(5, 5, 5)
                              .addComponent(txtEndYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addGroup(siteInfoPanelLayout.createSequentialGroup()
                              .addComponent(jLabel62)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel61)
                              .addGap(5, 5, 5)
                              .addComponent(txtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addGroup(siteInfoPanelLayout.createSequentialGroup()
                              .addGap(17, 17, 17)
                              .addComponent(btnSave)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(btnDeleteAll))))
                     .addGroup(siteInfoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addGap(5, 5, 5)
                        .addComponent(txtCrossDaters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addGap(5, 5, 5)
                        .addComponent(txtNumSamples, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addGap(5, 5, 5)
                        .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addGap(5, 5, 5)
                        .addComponent(txtTownship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addGap(5, 5, 5)
                        .addComponent(txtSpeciesName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addGap(5, 5, 5)
                        .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel37)
                        .addGap(5, 5, 5)
                        .addComponent(txtCounty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addContainerGap(35, Short.MAX_VALUE))
               .addGroup(siteInfoPanelLayout.createSequentialGroup()
                  .addGroup(siteInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(0, 0, Short.MAX_VALUE))))
      );

      jTabbedPane1.addTab("Site Information", siteInfoPanel);

      jLabel27.setText("Please Choose Entry Sample ID:");

      cmbSampleID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));

      dataEntryDataList.setModel(new javax.swing.AbstractListModel()
      {
         String[] strings = { "1850                           Dormant season scar", "1851                           Late earlywood scar", "1852                           Late earlywood scar", "1853                           Late earlywood scar", "1854                           Null year", "...                                ..." };
         public int getSize() { return strings.length; }
         public Object getElementAt(int i) { return strings[i]; }
      });
      jScrollPane4.setViewportView(dataEntryDataList);

      jLabel65.setText("Year");

      jLabel66.setText("Previous Value");

      jTextArea1.setEditable(false);
      jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
      jTextArea1.setColumns(20);
      jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
      jTextArea1.setRows(5);
      jTextArea1.setText("To change the value stored for a given year, select  the desired year on the left and then\nchoose a new value from the dropdown box below. Selecting the \"Fill 50 Years\" Value will \nautomatically fill the next 50 years with the value currently selected in the dropdown box.");
      jScrollPane1.setViewportView(jTextArea1);

      cmbNewValue.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Null year", "Pith year", "Bark year", "Inner ring", "Outer ring", "Dormant season scar", "Early earlywood scar", "Middle earlywood scar", "Late earlywood scar", "Undtermined season scar", "Early earlywood injury", "Middle earlywood injury", "Late earlywood injury", "Latewood injury", "undetermined season injury", "Recorder Year" }));

      jLabel28.setText("New Value");

      btnFillFifty.setText("Fill 50 Years");

      javax.swing.GroupLayout fireHistoryPanelLayout = new javax.swing.GroupLayout(fireHistoryPanel);
      fireHistoryPanel.setLayout(fireHistoryPanelLayout);
      fireHistoryPanelLayout.setHorizontalGroup(
         fireHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(fireHistoryPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(fireHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(fireHistoryPanelLayout.createSequentialGroup()
                  .addComponent(jLabel27)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(cmbSampleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(fireHistoryPanelLayout.createSequentialGroup()
                  .addGroup(fireHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(fireHistoryPanelLayout.createSequentialGroup()
                        .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(47, 47, 47)
                  .addGroup(fireHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(cmbNewValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel28)
                     .addComponent(btnFillFifty, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap(92, Short.MAX_VALUE))
      );
      fireHistoryPanelLayout.setVerticalGroup(
         fireHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(fireHistoryPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(fireHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel27)
               .addComponent(cmbSampleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
            .addGroup(fireHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(fireHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(fireHistoryPanelLayout.createSequentialGroup()
                  .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(119, 119, 119)
                  .addComponent(jLabel28)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(cmbNewValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btnFillFifty)))
            .addContainerGap())
      );

      jTabbedPane1.addTab("Fire History ", fireHistoryPanel);

      jLabel67.setText("Sample ID length");

      firstYearTextField.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            firstYearTextFieldActionPerformed(evt);
         }
      });

      numberOfSamplesTextField.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            numberOfSamplesTextFieldActionPerformed(evt);
         }
      });

      cancelBtn.setText("Cancel");

      saveDataSetBtn1.setText("Save");

      jLabel68.setText("First year of the data set");

      jLabel69.setText("Last year of the data set");

      jLabel70.setText("Number of Samples");

      jLabel71.setText("New File Name");

      javax.swing.GroupLayout dataSettingsPanelLayout = new javax.swing.GroupLayout(dataSettingsPanel);
      dataSettingsPanel.setLayout(dataSettingsPanelLayout);
      dataSettingsPanelLayout.setHorizontalGroup(
         dataSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(dataSettingsPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(dataSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(sampleIDLengthTextField, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(numberOfSamplesTextField, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(lastYearTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jLabel69, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(firstYearTextField, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jLabel68, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
               .addComponent(sampleIDLengthTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(dataSettingsPanelLayout.createSequentialGroup()
                  .addGroup(dataSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel71)
                     .addComponent(jLabel67)
                     .addComponent(jLabel70)
                     .addGroup(dataSettingsPanelLayout.createSequentialGroup()
                        .addComponent(saveDataSetBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
      );
      dataSettingsPanelLayout.setVerticalGroup(
         dataSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(dataSettingsPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel68)
            .addGap(4, 4, 4)
            .addComponent(firstYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel69)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lastYearTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel70)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(numberOfSamplesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel67)
            .addGap(3, 3, 3)
            .addComponent(sampleIDLengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel71)
            .addGap(3, 3, 3)
            .addComponent(sampleIDLengthTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(dataSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(saveDataSetBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(285, 285, 285))
      );

      jTabbedPane1.addTab("Data Settings ", dataSettingsPanel);

      jMenu1.setText("File");

      mnuImportData.setText("Import Data");
      jMenu1.add(mnuImportData);

      mnuSaveFile.setText("Save File");
      jMenu1.add(mnuSaveFile);

      jMenuBar1.add(jMenu1);

      jMenu2.setText("Help");
      jMenuBar1.add(jMenu2);

      setJMenuBar(jMenuBar1);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jTabbedPane1)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void firstYearTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_firstYearTextFieldActionPerformed
   {//GEN-HEADEREND:event_firstYearTextFieldActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_firstYearTextFieldActionPerformed

   private void numberOfSamplesTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numberOfSamplesTextFieldActionPerformed
   {//GEN-HEADEREND:event_numberOfSamplesTextFieldActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_numberOfSamplesTextFieldActionPerformed

    private void txtSiteNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSiteNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSiteNameActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[])
   {
      /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try
      {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
         {
            if ("Nimbus".equals(info.getName()))
            {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex)
      {
         java.util.logging.Logger.getLogger(HomeGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex)
      {
         java.util.logging.Logger.getLogger(HomeGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex)
      {
         java.util.logging.Logger.getLogger(HomeGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex)
      {
         java.util.logging.Logger.getLogger(HomeGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
        //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new HomeGui().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnDeleteAll;
   private javax.swing.JButton btnFillFifty;
   private javax.swing.JButton btnSave;
   private javax.swing.JButton cancelBtn;
   private javax.swing.JComboBox cmbNewValue;
   private javax.swing.JComboBox cmbSampleID;
   private javax.swing.JList dataEntryDataList;
   private javax.swing.JPanel dataSettingsPanel;
   private javax.swing.JPanel fireHistoryPanel;
   private javax.swing.JTextField firstYearTextField;
   private javax.swing.JPanel homePanel;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel10;
   private javax.swing.JLabel jLabel11;
   private javax.swing.JLabel jLabel12;
   private javax.swing.JLabel jLabel13;
   private javax.swing.JLabel jLabel14;
   private javax.swing.JLabel jLabel15;
   private javax.swing.JLabel jLabel16;
   private javax.swing.JLabel jLabel17;
   private javax.swing.JLabel jLabel18;
   private javax.swing.JLabel jLabel19;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel20;
   private javax.swing.JLabel jLabel21;
   private javax.swing.JLabel jLabel22;
   private javax.swing.JLabel jLabel23;
   private javax.swing.JLabel jLabel24;
   private javax.swing.JLabel jLabel25;
   private javax.swing.JLabel jLabel26;
   private javax.swing.JLabel jLabel27;
   private javax.swing.JLabel jLabel28;
   private javax.swing.JLabel jLabel29;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel30;
   private javax.swing.JLabel jLabel31;
   private javax.swing.JLabel jLabel32;
   private javax.swing.JLabel jLabel33;
   private javax.swing.JLabel jLabel34;
   private javax.swing.JLabel jLabel35;
   private javax.swing.JLabel jLabel36;
   private javax.swing.JLabel jLabel37;
   private javax.swing.JLabel jLabel38;
   private javax.swing.JLabel jLabel39;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel40;
   private javax.swing.JLabel jLabel41;
   private javax.swing.JLabel jLabel42;
   private javax.swing.JLabel jLabel43;
   private javax.swing.JLabel jLabel44;
   private javax.swing.JLabel jLabel45;
   private javax.swing.JLabel jLabel46;
   private javax.swing.JLabel jLabel47;
   private javax.swing.JLabel jLabel48;
   private javax.swing.JLabel jLabel49;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel50;
   private javax.swing.JLabel jLabel51;
   private javax.swing.JLabel jLabel52;
   private javax.swing.JLabel jLabel53;
   private javax.swing.JLabel jLabel54;
   private javax.swing.JLabel jLabel55;
   private javax.swing.JLabel jLabel56;
   private javax.swing.JLabel jLabel57;
   private javax.swing.JLabel jLabel58;
   private javax.swing.JLabel jLabel59;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel60;
   private javax.swing.JLabel jLabel61;
   private javax.swing.JLabel jLabel62;
   private javax.swing.JLabel jLabel63;
   private javax.swing.JLabel jLabel64;
   private javax.swing.JLabel jLabel65;
   private javax.swing.JLabel jLabel66;
   private javax.swing.JLabel jLabel67;
   private javax.swing.JLabel jLabel68;
   private javax.swing.JLabel jLabel69;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel70;
   private javax.swing.JLabel jLabel71;
   private javax.swing.JLabel jLabel72;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JMenu jMenu1;
   private javax.swing.JMenu jMenu2;
   private javax.swing.JMenuBar jMenuBar1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane4;
   private javax.swing.JSeparator jSeparator1;
   private javax.swing.JSeparator jSeparator2;
   private javax.swing.JSeparator jSeparator3;
   private javax.swing.JTabbedPane jTabbedPane1;
   private javax.swing.JTextArea jTextArea1;
   private javax.swing.JTextField lastYearTextField1;
   private javax.swing.JMenuItem mnuImportData;
   private javax.swing.JMenuItem mnuSaveFile;
   private javax.swing.JTextField numberOfSamplesTextField;
   private javax.swing.JTextField sampleIDLengthTextField;
   private javax.swing.JTextField sampleIDLengthTextField1;
   private javax.swing.JButton saveDataSetBtn1;
   private javax.swing.JPanel siteInfoPanel;
   private javax.swing.JTextField txtAreaSampled;
   private javax.swing.JTextField txtAspect;
   private javax.swing.JTextField txtCollectors;
   private javax.swing.JTextField txtCommonName;
   private javax.swing.JTextField txtCountry;
   private javax.swing.JTextField txtCounty;
   private javax.swing.JTextField txtCrossDaters;
   private javax.swing.JTextField txtEndYear;
   private javax.swing.JTextField txtHabitatType;
   private javax.swing.JTextField txtHighestElev;
   private javax.swing.JTextField txtLatitude;
   private javax.swing.JTextField txtLongtitude;
   private javax.swing.JTextField txtLowestElevation;
   private javax.swing.JTextField txtNationalForest;
   private javax.swing.JTextField txtNumSamples;
   private javax.swing.JTextField txtParkMonument;
   private javax.swing.JTextField txtQuarterSection;
   private javax.swing.JTextField txtRange;
   private javax.swing.JTextField txtRangerDistrict;
   private javax.swing.JTextField txtSection;
   private javax.swing.JTextField txtSiteCode;
   private javax.swing.JTextField txtSiteName;
   private javax.swing.JTextField txtSlope;
   private javax.swing.JTextField txtSpeciesName;
   private javax.swing.JTextField txtStartYear;
   private javax.swing.JTextField txtState;
   private javax.swing.JTextField txtSubstrateType;
   private javax.swing.JTextField txtTopographicMap;
   private javax.swing.JTextField txtTownship;
   private javax.swing.JTextField txtUTMEasting;
   private javax.swing.JTextField txtUTMNorthing;
   // End of variables declaration//GEN-END:variables
}
